- app.js
Add `requestNotificationPermission()` to `handleSignIn()`, `handleCreateAccount()` and `handleImportFile()`
> Add notification permission request

- app.js
- index.html
- log-utils.js
- service-worker.js
- styles.css
Summary:
This PR adds a logging system to help track important application events and debug issues:
Key Changes:
- Added log-utils.js for storing logs in IndexedDB
- Direct logging methods: Logger.log(), Logger.warn(), Logger.error()
- Batches logs for performance (saves every 5s or 100 items)
- Auto-saves on page unload/errors
- Maintains log order with unique IDs
Added logs viewer UI:
- New "View Logs" option in menu
- Modal with refresh/clear functionality
- Color-coded log levels (info/warn/error)
- Shows timestamp and source file info
- Auto-scrolls to latest logs
Service Worker Integration:
- Added logging for lifecycle events
- Captures message polling and notification states
- Saves logs before termination
Added styles for log viewer interface
- Monospace font for better …
>  Add persistent logging system with IndexedDB storage and UI viewer

- app.js
- log-utils.js
Summary:
Remove unused checks in log-util and add additional invoked Logger methods
Logger methods invoked for
- App visibility state changes
- Notification permission changes
- App state management events
Cleaned up log-utils.js:
- Removed unnecessary favicon.ico filtering
- Simplified service worker context detection
- Streamlined source file detection
- Removed redundant comments and error handling
Improved error handling:
- Added logging for notification permission denials
- Enhanced error logging for service worker registration
- Better visibility state change tracking
> Remove unused checks in log-util and add Loggers

- app.js
- data_structures_flow/CoreDataStructures.md
- data_structures_flow/chat-search-flow.md
- data_structures_flow/contacts-search-flow.md
- data_structures_flow/core-data-structures.md
- data_structures_flow/message-data-structures.md
- data_structures_flow/notifications-ds-flow.md
- data_structures_flow/search-refactor.md
- index.html
- network.js
- styles.css
- Added new contact search functionality parallel to message search
- Implemented dynamic debounce timing for search inputs (600ms for single char, 300ms for multiple)
- Unified empty state handling across search features
- Renamed `handleChatClick` to `handleResultClick` for better clarity
- Real-time contact search across multiple fields (username, name, email, phone, linkedin, x)
- Smart result sorting (exact matches > starts with > contains)
- Highlighted search matches in results
- Consistent UI between message and contact search
- Added new `searchContacts()` function with relevance-based sorting
- Implemented `displayContactResults()` with field-specific match highlighting
- Updated debounce function to support dynamic wait times
- Unified empty state handling through …
> Add Contact Search Feature

- app.js
- data_structures_flow/CoreDataStructures.md
- data_structures_flow/chat-search-flow.md
- data_structures_flow/core-data-structures.md
- data_structures_flow/message-data-structures.md
- data_structures_flow/notifications-ds-flow.md
- index.html
- network.js
- styles.css
- Added persistent search bar in chat view
- Implemented real-time message search across all contacts
- Added search modal with detailed results view
- Introduced message highlighting when navigating to search results
- Global message search across all contacts
- Real-time search with smart debouncing (600ms for single char, 300ms for multiple)
- Results show message preview with context ("You:" prefix for sent messages)
- Smooth navigation to found messages with temporary highlighting
- Added `searchMessages()` function to search across all contacts' messages
- Implemented `debounce()` with dynamic timing based on input length
- Added `handleSearchResultClick()` for result navigation
- New `handleChatClick()` implementation for viewing specific messages
- New persistent search bar below …
> Add Messsage Search Feature

- app.js
- service-worker.js
Summary: changes to have better logging for websocket, comment out Logger, add `initializeWebSocketManager` to initialize with useful logging and checks
• WebSocket Management Improvements:
- Refactored WSManager class with more robust connection handling
- Added WebSocket support detection for different browsers
• Polling System Updates:
- Improved fallback polling mechanism when WebSocket fails
- improve logging 
• Camera permission try catch with toast
• Code Cleanup:
- Removed Logger calls throughout the codebase (may have been causing silent errors due recent service-worker logic)
- Improved error handling and reporting
- Better handling of subscription states
- Added detailed diagnostic information for debugging
• Connection Management:
- Added new initializeWebSocketManager …
> Refactor WebSocket connection handling, improve logging, and wallet update bug

- app.js
- network.js
- network.js_loc
- network.js_web
- Removed redundant unsubscribe calls during WebSocket disconnection.
- Simplified WebSocket subscription and unsubscription message formats.
- Enhanced logging for subscription confirmation and error handling.
- Cleaned up redundant code
> Refactor WebSocket management and improve subscription handling

- styles.css
- Changed the background color of the active navigation button to a darker shade.
- Commented out the active button's underline styles for potential future use.
> Update active button styles in CSS to be darker

- app.js
- index.html
- styles.css
- Removed the dropdown menu for contact options and replaced it with a direct 'Add Friend' button.
- Updated event listeners and styles to reflect the new button functionality.
- Enhanced the appearance of the friend button based on friend status, including hover effects and icon updates.
> Refactor contact info modal by removing dropdown menu and move add friend button

- app.js
- index.html
- styles.css
- Refactored contact name editing to use persistent event listeners
- Added inline editing capability in the edit contact modal
- Changed edit field layout from row-reverse to row
- Updated save button icon from plus to checkmark
- Added margin between input field and action button
- Removed duplicate save button icon style
- Moved event listeners to `DOMContentLoaded` for better performance
- Added handlers for input, keydown, and button click events
- Implemented proper name handling for empty/null values
- Added focus management for the name input field
- Improved modal state management and cleanup
- Fixed modal cleanup by removing unnecessary menu dropdown reference
- Added safety checks for modal element existence
- Improved handling of "Not provided" default name state
- Separated …
> Enhance edit contact modal 

- index.html
On the Menu rename Export to Backup and on the Login screen rename Import Account to Restore Account
> Update text for `importAccountButton` `openExportForm` and `modal-title`

- app.js
> Don't append signin button if no accounts

- app.js
- index.html
- styles.css
- Introduced a new button for sending money in the contact info section.
- Implemented event handler to open the send money modal.
- Enhanced modal behavior to pre-populate username if the contact info modal is active.
- Adjusted CSS for the new button and modified layout for better spacing.
> Add send money button and modal functionality

- app.js
- index.html
- styles.css
* move html order of contactInfoModal to set correct z-index.
* Update send money button to pre-populate username from contact info modal.
* Refactor openSendModal function to handle username input more efficiently and reset after use.
* Clean up z-index styles in CSS for better modal layering.
> Reposition contactInfoModel (z-index) and enhance send money functionality

- index.html
> Update modal title from "Export Data" to "Backup Data"

- app.js
- data_structures_flow/qr-code-flow.md
- index.html
- New file upload button next to existing QR scanner button
- File upload functionality to process QR codes from images
- Added event listeners for file upload button and file input
- Created `handleQRFileSelect` function to process uploaded images
- Reuses existing `handleSuccessfulScan` function for QR code data handling
- Uses HTML5 Canvas to process uploaded images
- Utilizes jsQR library for QR code detection
- Handles file cleanup with `URL.revokeObjectURL`
- Provides user feedback through toast messages
- Works on desktop browsers
- Works on iOS PWA
- Works on Android PWA
- Added file input element in HTML
- Added file upload button with appropriate icon
- Added file processing logic in JavaScript
- Fixed code formatting in `contactInfoSendButton` handler
- Verified file upload …
> add QR code upload functionality, and enhance qr-code documentation

- app.js
When switching between tabs (chats, contacts, wallet), the content changes immediately but the tab highlight visibly lags behind, creating a perception of poor performance.
The tab highlight was being updated at the end of the `switchView` function, after multiple async operations were triggered but before they completed. This caused a noticeable delay between the content change and the visual feedback in the navigation.
Additionally, the implementation used inefficient DOM querying with `querySelectorAll` which further contributed to the lag.
1. **Immediate Visual Feedback**
- Moved tab highlight updates to the beginning of the function
- Tab now gets highlighted immediately when clicked, before async data loading begins
2. **Direct DOM References**
- Replaced `querySelectorAll` calls …
> Fix - Lagging switch animations between screens

- app.js
Prevent double sending message by disabling button for sending chat when processing
Problem: The chat "Send" button remained active while a message was being sent. 
- This allowed users to click it multiple times, potentially sending duplicate messages or causing errors.
Solution:
The "Send" button is now disabled immediately when clicked (handleSendMessage function starts).
A finally block ensures the button is re-enabled after the sending process completes, whether it succeeds or fails.
> Disable button for sending chat when processing

- app.js
- index.html
- network.js
- styles.css
**Summary:**
This PR introduces real-time balance validation on the "Send Asset" form, ensuring users have sufficient funds, including the transaction fee, before attempting a transfer.
**Key Changes:**
*   **Real-time Balance Validation:** The available balance is now checked as the user types the amount, including the required network fee.
*   **Fee Display:** The estimated transaction fee is displayed separately below the available balance.
*   **Insufficient Balance Warning:** A clear warning message appears if the entered amount plus the fee exceeds the available balance.
*   **Send Button Disabled:** The "Send" button is disabled if the user has insufficient funds.
*   **Improved "Fill Amount":** Clicking the available balance now fills the amount input with the maximum sendable …
> validate balance before enabling send button

- index.html
User may think clear cache will clear your localStorage/accounts.`Check Update` is more appropriate.
> Update button label from "Clear Cache" to "Check Update" 

- app.js
- index.html
- styles.css
**PR Summary: UI/UX Improvements and Network Config Update**
This PR introduces several improvements to the user interface and updates the default network configuration:
1.  **Welcome Screen Button Visibility:** Refactored the logic for showing/hiding buttons on the welcome screen (`signInButton`, `createAccountButton`, etc.) in `index.html` and `app.js`. Buttons are now hidden by default using a new `.hidden` CSS class (`styles.css`) and explicitly shown via JavaScript based on account status. This prevents buttons from briefly flashing before their correct state is determined.
2.  **QR Code Handling Enhancements (`app.js`):**
*   When filling payment details from a QR scan (`fillPaymentFromQR`), the amount field now also triggers validation immediately.
*   Improved the file-based QR …
> Improve Welcome Screen and QR Scan UX

- app.js
- index.html
**Title:** Fix: Resolve QR Code Overflow and Optimize Payload
**Summary:**
*   **Fix QR Code Overflow:** Resolves the "code length overflow" error when generating QR codes with long memos by **optimizing the data payload**.
*   **Optimize QR Data Payload:** Refactored QR code generation (`createQRPaymentData`), processing (`processQRData`), preview (`previewQRData`), and form filling (`fillPaymentFromQR`) to use **short JSON keys** (e.g., `u` for username, `m` for memo), significantly reducing payload size.
*   **Improve QR Fallback:** Updated the fallback QR code (generated on error) to use the **standard `liberdus://` format** with the short username key (`u`), ensuring better compatibility with the scanner.
*   **Enhance Cache Clearing:** Improved the "Check Update" functionality to …
> Refactor QR Code Data Handling

- app.js
*   **Account Creation UI Enhancements:**
*   Added a toast notification to inform the user that account creation is in progress.
*   Disabled the "Create Account" button during the creation process to prevent multiple submissions.
*   Re-enabled the button after the creation attempt (Note: Currently includes a placeholder 3-second delay instead of checking for actual success).
*   **Send Modal Balance Update:**
*   Modified `openSendModal` to be asynchronous.
*   Ensured wallet balances are refreshed (`updateWalletBalances`) immediately upon opening the Send modal, providing the user with the most current balance information.
> Enhance Account Creation Feedback and Update Send Modal Balances

- styles.css
* Added CSS properties to allow breaking long words and ensure proper text wrapping in file input elements.
> Enhance transaction history memo wrapping

- app.js
- lib.js
* Add HTML escaping in linkifyUrls function to prevent XSS vulnerabilities and ensure safe display of URLs.
* Update chat message rendering to use linkifyUrls for converting plain text URLs into clickable links.
* Modify transaction history display to linkify memo text, improving user experience.
> Prevent html text rendering in chatList, chatModal, transactionHistoryModal, and searchModal

- app.js
**Refactor: Prevent Multiple Listeners on Username Input**
*   Extracted the username input handling logic (including debounced availability check) from `openCreateAccountModal` into a dedicated function `handleCreateAccountInput`.
*   Moved the event listener attachment for the `#newUsername` input to the `DOMContentLoaded` handler. This ensures the listener is attached only once when the DOM is ready, preventing duplicate listeners from being created each time `openCreateAccountModal` was called.
*   Improved code organization and robustness.
> Prevent Multiple Listeners on Username Input due to `openCreateAccountModal`

- app.js
*   Removed unused code and properties related to an obsolete inline edit feature (`enterEditMode`, `exitEditMode`, `isEditing`, etc.).
*   Consolidated all necessary event listener attachments (`back-button`, `addFriendButton`, `nameEditButton`, `closeEditContactModal`, `contactInfoChatButton`) into the `setupEventListeners` method, ensuring they are attached only once during initialization.
*   Simplified the back button listener logic.
*   Modified `setupChatButton` to only manage button visibility, separating it from listener attachment.
*   Fixed a bug where the chat button listener would cause an error by closing the modal before capturing the necessary contact address for `openChatModal`.
> Refactor: Simplify Contact Info Modal Event Handling & Remove unused code

- app.js
*   Replaced the `initializeSearch` function with dedicated event handlers (`handleSearchInputClick`, `handleMessageSearchInput`) attached directly in `DOMContentLoaded`.
*   Separated logic for opening the search modal (`handleSearchInputClick`).
*   Separated logic for handling debounced text input and triggering search (`handleMessageSearchInput`).
*   Removed the `displayLoadingState` function; loading state since was not getting used and not invoked at all
> Refactor Search Event Handling

- styles.css
chatlList chat-message styling to not overflow and stay on one line. 
searchResults chat-message should overflow when searching for messages.
> Update chat message styles for search results and general chat display

- app.js
- Retrieve private key from `localStorage` instead of `existingAccounts`. 
- Simplified code by removing redundant lines while maintaining functionality for account recreation.
> Refactor handleSignIn function to retrieve private key from `localStorage`

- app.js
This PR introduces significant changes to WebSocket connection handling
*   **WebSocket Management Refactoring:**
*   Moved the `initializeWebSocketManager` function into the `WSManager` class as a method.
*   Centralized the responsibility of initializing, connecting, and subscribing to the WebSocket within the `WSManager.initializeWebSocketManager` method.
*   Removed scattered calls to initialize WebSockets from `handleCreateAccount`, `handleSignIn`, and `DOMContentLoaded`.
*   Added a call to `wsManager.initializeWebSocketManager()` within the `switchView` function to ensure the WebSocket connection is managed appropriately when changing application views.
*   Simplified the logic for attempting WebSocket connections in `pollChats`.
*   Adjusted the timing of `setupEventHandlers` call …
> Refactor WebSocket Management

- app.js
removed getColorFromHash, already present in lib.js and used instead in lib.js
> Remove unused color generation function from app.js

- app.js
- remove JSON parsing in handleImportFile
- remove unused SALT generation
- removed unused username input in newChatModal
> Remove unused code

- app.js
The `checkTimeout` variable has to be declared outside of the function. - Jai 
- Refactor username input handling in app.js. Introduced a dedicated timeout variable, `usernameInputCheckTimeout`, for username availability checks, improving clarity and preventing potential conflicts with previous timeouts.
> Dedicated timeout variable ,`usernameInputCheckTimeout`, for `handleUsernameInput`

- lib.js
Added HTML escaping using the escapeHtml function to the linkifyUrls function.
> fix(linkifyUrls): improve URL detection and sanitization with escapeHtml function

- app.js
Updated the version alert in the `checkVersion` function to include version details in `app.js`
> Update versioning in app.js to reflect new release identifier and enhance version update alert message

- app.js
* Implemented lockToPortrait function to attempt locking the screen orientation to portrait. Added error handling to log any issues encountered during the locking process.
* Updated DOMContentLoaded event to call lockToPortrait, ensuring the orientation is set when the page loads.
> Add Screen API function to lock screen orientation to portrait mode in app.js

- app.js
**Summary:**
*   Updates the payment history modal to display contact information more consistently with other parts of the app.
*   The logic now prioritizes showing the contact's details in the following order:
1.  The name manually assigned to the contact (`contact.name`).
2.  The name provided by the contact in their sender info (`contact.senderInfo?.name`).
3.  The contact's registered username (`contact.username`).
4.  A truncated version of the contact's address (`address.slice(0,8)...address.slice(-6)`), as a fallback.
*   Optional chaining (`?.`) is used to safely access potentially missing properties like `senderInfo` or the contact object itself.
> Improve Contact Display in Transaction History

- app.js
- styles.css
* Updated contact rendering in updateContactsList function to use a new class for displaying contact information, enhancing clarity and consistency in the UI.
* Introduced new CSS styles for .contact-list-info to improve the visual presentation of contact details, including font adjustments and text overflow handling.
> Refactor contact display in app.js and add new styles for contact list info

- index.html
- styles.css
Add clickable Liberdus logo links
This PR adds clickable links to the Liberdus website (https://liberdus.com) for both the header logo and welcome page logo.
Changes:
- Added links to both logos with target="_blank" to open in new tab
- Added title attributes for accessibility and tooltips
- Added consistent styling for both logo links using the .logo-link class
- Implemented hover effects to indicate clickability
The logos now provide a clear way for users to visit the main Liberdus website while maintaining a consistent look and feel throughout the application.
> Enhance logo links in index.html

- app.js
**Summary:**
*   **Task:** Improve the accuracy of client-side timestamps by adjusting them based on the difference between the client's clock and a reliable server time.
*   **Solution:**
*   Introduced a global variable `timeSkew` to store the calculated difference (in milliseconds) between server time and client time.
*   Created an async function `timeDifference` that:
*   Fetches the current UTC time from `worldtimeapi.org`.
*   Calculates the difference (`skew`) between the server time and `Date.now()`.
*   Stores the calculated difference in the global `timeSkew`.
*   Logs the difference for debugging.
*   Added a call to `await timeDifference()` early in the `DOMContentLoaded` listener to calculate the skew on page load.
*   Implemented a new function `getCorrectedTimestamp()` …
> Implement Client Time Correction Using Server Time Skew

- app.js
- index.html
- styles.css
- **WebSocket Status Indicator**
- Added a new `<div id="wsStatusIndicator" class="ws-status-indicator">` to the header for real-time WebSocket connection status.
- Implemented `updateWebSocketIndicator()` in `app.js` to update the indicator color and text based on connection/subscription state.
- Called `updateWebSocketIndicator()` on all relevant WebSocket events and on a timer for robustness.
- Added corresponding CSS styles for red (disconnected), yellow (connected, not subscribed), and green (connected and subscribed) states.
---
**User Impact:**  
Users now see a clear, color-coded indicator of WebSocket connection status in the app header.
> Enhance WebSocket Connection Status Indicator

- app.js
* Remove previous export form functions and integrate their logic into a new BackupModal class for improved organization and maintainability.
* Implement event listeners for opening, closing, and submitting the export modal within the BackupModal class.
* Ensure data encryption and download functionality remains intact while enhancing the structure of the code.
> Refactor Export Modal Functionality into BackupModal Class

- app.js
- Removed standalone import-related functions (`openImportFileModal`, `closeImportFileModal`, `handleImportFile`)
- Implemented new `RestoreAccountModal` class to handle account restoration
- Maintained all existing functionality while improving code organization
The new `RestoreAccountModal` class encapsulates all import-related functionality:
- File reading and decryption
- Account data parsing and validation
- LocalStorage updates
- Success/error handling
- UI state management
Please verify:
1. Account restoration from both encrypted and unencrypted backup files
2. Successful login after account restoration
3. Proper error handling for invalid files or incorrect passwords
4. Correct updating of account list in the UI
- This change is part of a larger effort to modularize modal …
> Refactor Import Account Logic in RestoreAccountModal

- app.js
- index.html
- styles.css
This PR updates the Validator Options modal (`#validatorModal`) to dynamically fetch, calculate, and display relevant staking information when opened. It also introduces conditional logic based on whether the user has nominated a validator.
*   **`app.js`:**
*   Refactored `openValidatorModal` to be `async`.
*   Implemented concurrent fetching of user account data, network configuration data (`0x0...0` account), and market price using `Promise.all`.
*   Refactored `getMarketPrice` to `getMarketPrice`, which now retrieves the LIB market price from cached data in `myData` after ensuring the `updateAssetPricesIfNeeded` check runs.
*   Added logic to calculate derived values: Stability Factor, Minimum Stake in LIB, User Staked Amount in USD (based on market price), and Minimum Stake in USD …
> Implement Validator Modal Information Display

- app.js
* Consolidate gateway-related functionality into a new GatewayModal class for improved organization and maintainability.
* Replace multiple standalone functions with methods within the GatewayModal class, including opening, closing, and managing gateway forms.
* Update event listeners to utilize the new class methods, enhancing code clarity and reducing redundancy.
* Implement UI updates for gateway list management, including adding, editing, and removing gateways, with appropriate success messages.
* Ensure consistent handling of default gateway selection and UI state management across the application.
> Refactor Gateway Management into GatewayModal Class

- app.js
*   **Stake Modal:**
*   Use minimum stake amount from ID selector (`#validator-network-stake-lib`) to pre-fill in stake amount.
*   The stake amount input is now pre-filled with the minimum stake amount when the modal opens.
*   **Unstake Transaction (`submitUnstakeTransaction`):**
*   Increased toast duration to 8 seconds for the "submitting" message.
*   Disabled relevant buttons (unstake, back, submit stake) during the transaction submission and re-enabled them afterwards.
*   Removed manual UI updates and instead refreshes the validator modal by closing and reopening it upon success.
*   Added a delay after the API call before processing the response.
*   **Stake Transaction (`handleStakeSubmit`):**
*   Increased toast duration for the "submitting" message.
*   Disabled relevant …
> Refactor Validator Stake/Unstake Modals and Actions

- app.js
* Remove old About modal functions and replace them with a new AboutModal class for better organization and encapsulation.
* Implement event listeners for opening and closing the About modal within the new class.
* Set version and network information during initialization to streamline the user experience.
> Refactor About Modal Functionality in app.js

- app.js
- index.html
- styles.css
* Introduce MyProfileModal class to encapsulate account modal functionality, improving code organization and maintainability.
* Update event listeners for opening and closing the profile modal, and handle form submission within the class.
* Rename UI elements from "Account" to "Profile" for better clarity and user experience.
* Add a profile sharing note to the modal for enhanced user information.
* Refactor associated HTML and CSS to accommodate the new structure and improve layout consistency.
> Refactor Account Modal into MyProfileModal Class

- app.js
- index.html
- Replace success message display with toast notification and disable close button during profile update.
- Refactor event listener for close button for improved clarity.
- Added a reference to the submit button in the MyProfileModal class.
- Enhanced the handleSubmit method to disable the submit button during profile updates and re-enable it after a delay, improving user experience by preventing multiple submissions.
> Enhance MyProfileModal

- app.js
- index.html
We added a QR code upload button to the Stake Modal and refactored the JavaScript QR file processing to correctly populate fields for both stake and send actions.
**`index.html`:**
*   Added an "Upload QR" button (`uploadStakeQRButton`) alongside the "Scan QR" button within the Stake Modal's validator address input group.
*   Added a hidden file input (`stakeQrFileInput`) associated with the Stake Modal to handle QR code image uploads.
**`app.js`:**
*   Added a click event listener to `uploadStakeQRButton` to programmatically click the hidden `stakeQrFileInput`.
*   Refactored the `handleQRFileSelect` function:
*   Modified its signature to accept a `fillFunction` parameter.
*   Updated it to execute the passed `fillFunction` with the decoded QR data instead of always calling …
> Feat: Add QR Code Upload to Stake Modal

- app.js
Enhance the timeDifference function to fetch time from a network gateway endpoint instead of timeapi
-  improving accuracy in time skew calculations. 
- fixes cors error and less retries
- Implement robust error handling for network issues and clarify logging for better maintainability.
> Refactor timeDifference function for improved accuracy and error handling

- app.js
- Added `pending` array to `myData` data structure for tracking transaction status
- Implemented transaction object pushing in `injectTx()` function for `transfer` and `message` types
> Add pending transactions array

- app.js
- Added `data-txid` attributes to transaction elements in chat lists and message displays
- Enhanced chat items to include transaction IDs for better transaction tracking
- Added transaction ID attributes to payment and message UI elements for status tracking
- Refactored `injectTx()` to accept precomputed transaction IDs instead of keys
- Separated transaction signing from transaction submission process
- Implemented distinct signing step with `signObj()` before transaction injection
- Modified all transaction posting functions to follow the new pattern:
- `postChatMessage()`
- `postAssetTransfer()`
- `postRegisterAlias()`
- `postStake()`
- `postUnstake()`
- Added transactions to `myData.pending` array with complete metadata:
- Transaction ID
- Transaction type
- Submission timestamp
- …
> Improved Transaction Tracking and Signing. Add id to 'message' rendered 

- app.js
- Refactored chat message sending process by separating concerns:
- Created new `createChatMessage()` function to generate message objects
- Repurposed existing `injectTx()` function for transaction submission
- Removed direct usage of `postChatMessage()` in favor of this two-step approach
- Enhanced message tracking by storing transaction IDs:
- Added `txid` to message objects in UI
- Added `txid` to chat update objects
- Improved code documentation with JSDoc comments for related functions
> sendChatMessage Flow Refactoring

- app.js
* Move txid attribute declaration inside the map function for correct scope.
* Update transaction item rendering to use a block structure.
> FIX: Refactor transaction rendering in updateTransactionHistory function

- app.js
*   **Periodic Checking:** Introduced `setInterval` to call `checkPendingTransactions` every 5 seconds, automatically monitoring transaction statuses.
*   **Refactored Failure Handling:** Created a dedicated `removeFailedTx(txid)` function to consolidate the logic for removing failed transactions from `myData.pending`, contact messages, and `walletData.history`.
*   **Improved `checkPendingTransactions`:**
*   Added initialization for `myData.pending` if it doesn't exist.
*   Queries the network for the status of transactions older than 8 seconds.
*   Handles successful transactions by removing them *only* from the pending queue (no UI refresh needed here).
*   Handles failed transactions by calling `removeFailedTx` for data cleanup and then `refreshCurrentView` to update the UI.
* …
> Implement Pending Transaction Tracking and Status Updates

- app.js
- styles.css
**Transaction Status Tracking:**
- Added `status` attribute to track transaction life cycle ('sent', 'failed')
- Store transaction status in both message objects and transaction history
- Added transaction type tracking to support different status handling based on transaction type
**UI Enhancements:**
- Display visual indicators for failed transactions:
- Added exclamation mark icon for failed message bubbles
- Added red-bordered styling for failed transactions in history view
- Used data attributes (`data-status="failed"`) for semantic markup
- Prevent interaction with failed items:
- Disabled click-to-copy for failed messages
- Prevent clicking on failed transactions in history
**Error Handling:**
- Added toast notifications to display failure reasons from transaction receipts
- …
> Transaction Failure Tracking and UI Improvements

- app.js
Refactor error handling in transaction functions and clean up commented code
* Comment out error handling logic in handleSendAsset and handleSendMessage for clarity.
* Update injectTx function to conditionally push transactions to pending only on success, improving error feedback.
* Enhance logging for transaction injection errors to aid debugging.
* Clean up commented-out code to improve readability and maintainability.
> Refactor injectTx error handling in handleSendMessage and handlesSendAsset

- app.js
Enhance transaction history display by including nominee information and improve address validation in history item click handler. Additionally, update stake submission logic to include nominee details in transaction history, ensuring better tracking of transactions.
> Add stakeTx into myData.wallet.history for historyModal

- app.js
*   **Refactor Account Creation (`handleCreateAccount`):**
*   Replaced `setTimeout` with a robust polling mechanism using `checkPendingTransactions` and a new `pendingPromiseService` to wait for registration transaction confirmation.
*   Improved UX with persistent loading toasts during account creation and clear success/error feedback.
*   Ensures UI state (e.g., submit button) correctly reflects the ongoing process and final outcome.
*   **Enhance Pending Transaction Logic (`checkPendingTransactions`):**
*   Overhauled the function to reliably check the status of pending transactions via the `/transaction/{txid}` endpoint.
*   Handles success, failure, and timeout scenarios for different transaction types (`register`, `deposit_stake`, `withdraw_stake`, `transfer`, `message`).
* …
> Improve Account Creation with Pending Confirmation

- app.js
Implement interval management for transaction updates in handleCreateAccount function. Add logic to start and clear intervals for updating WebSocket indicators and checking pending transactions, enhancing user feedback during account creation.
> Fix: handleCreateAccount stuck due to not starting interval for pending tx check

- app.js
Update submitStake button text based on nominee presence in openStakeModal function. The button now displays "Add Stake" if a nominee is set, enhancing clarity for users during staking operations.
> Update submitStake button text based on nominee presence in openStakeModal

- app.js
Enhance app functionality with visibility change handling and sound notifications
* Updated handleVisibilityChange function to be asynchronous, allowing for state saving and chat data updates when the document visibility changes.
* Added vibration feedback to playChatSound and playTransferSound functions to enhance user experience during notifications.
> Fix/visibility change getChat to get new chats

- app.js
- index.html
- styles.css
- Updated the `tollModal` class in app.js to include functionality for toggling between LIB and USD currencies when setting a new toll amount.
- Added validation to ensure the new toll amount is a valid number and provides user feedback for invalid entries.
- Enhanced the UI in index.html to support the new currency toggle feature, including a button for switching currencies and improved input handling.
- Adjusted styles in styles.css to ensure consistent design for the new toll input field and toggle button.
> Implement `tollModal` currency toggle and validation features

- app.js
- Renamed `saveNewToll` to `saveAndPostNewToll` for clarity and updated its implementation to include posting the new toll to the network.
- Introduced `postToll` method to handle network transactions for toll submissions.
- Added error handling for failed toll submissions, reverting to the previous toll value if necessary.
- Updated event listeners and modal interactions to reflect the new method names and functionalities.
> Refactor TollModal to implement toll submission process and error handling

- styles.css
- Introduced a new focus style for form controls to be uniform with a purple border.
- Removed the border from the file input field since interfering with purple border in sendModal.
> Add common focus style for form controls in styles.css

- app.js
Problem: validation for each input were working independently. 
Fix send modal input-validation with refreshSendButtonDisabledState function
- Introduced a new function to manage the disabled state of the send button based on address validity and balance validation.
- Updated `handleOpenSendModalInput` to call `refreshSendButtonDisabledState` for improved button state management.
- Refactored `updateAvailableBalance `to ensure button state reflects asset availability and balance validation.
- Adjusted `validateBalance` to return true for sufficient balance, streamlining the validation logic.
> Fix send modal input-validation with refreshSendButtonDisabledState function

- app.js
- Updated console logging to use console.warn for asset availability warnings.
- Simplified UI reset comments for clarity.
- Consolidated pending transaction text handling into a single conditional statement.
- Refactored data extraction to accommodate changes in API response types, ensuring proper handling of BigInt objects.
- Enhanced error logging for better debugging of user staked amounts and market stake calculations.
> fix: Validator Modal handling new queryNetwork parsing correctly

- app.js
- Added `updateTollValue` function to asynchronously query and update the contact's toll value from the network when the chat modal is opened.
- Enhanced `openChatModal` to set the address data attribute and trigger the toll value update without awaiting its completion.
- Improved documentation with JSDoc comments for better clarity on function purposes and parameters.
> feat: Implement toll value update in chat modal

- app.js
- Renamed `updateContactToll` to `updateTollRequired` for clarity and updated its logic to improve toll value management.
- Introduced `updateTollAmountUI` function to centralize the UI update for toll values in the chat modal.
- Removed direct DOM manipulation from `openChatModal` and `updateTollValue`, ensuring a cleaner separation of concerns.
- Updated documentation to reflect the changes in function names and their purposes.
> feat: introduce `updateTollAmountUI` to handle displaying toll amount

- app.js
- Improved the `updateTollAmountUI` function to display toll values in both LIB and USD, incorporating a conversion factor for accurate representation.
- Updated the `updateTollValue` function to check for changes in both toll and toll unit, ensuring the UI reflects the most current data.
- Streamlined the display logic for required and free tolls, enhancing user clarity in the chat modal.
> refactor: Enhance toll amount UI and update logic in `updateTollValue()`

- app.js
- Removed redundant network query for contact toll data in `openChatModal`, initializing toll and tollUnit to null.
- Enhanced `updateTollAmountUI` to set toll and tollUnit from the contact data, ensuring accurate display.
- Modified `validateBalance` to accept an optional asset index, improving flexibility in balance checks.
- Updated `handleSendMessage` to validate sufficient balance for toll before sending messages, enhancing user feedback on balance requirements.
> Update toll handling and validation in handleSendMessageand balance functions

- app.js
- Moved friend management logic from ContactInfoModalManager to a new FriendModal class for better organization and maintainability.
- Implemented event listeners for the Friend Modal, including opening, closing, and form submission.
- Updated the friend status handling to prepare for future enhancements, including changing the status representation from boolean to a numeric system.
- Removed redundant code from ContactInfoModalManager, streamlining its responsibilities.
> refactor: Separate Friend Modal functionality into its own class

- app.js
- Introduced a new property `oldFriend` to track the previous friend status before updates.
- Integrated the chat toll update transaction into the friend submission process, ensuring proper handling of transaction failures.
- Updated error handling to revert the friend status to the previous value in case of a failed chat toll update, improving user feedback and data integrity.
> Enhance friend status update logic in FriendModal

- app.js
- index.html
- Added `setAddress` method in FriendModal to manage current contact address.
- Updated `openChatModal` and `ContactInfoModalManager` to utilize the new `setAddress` method.
- Refactored event listeners for adding friends, differentiating between chat and contact info contexts.
- Modified HTML to include distinct buttons for adding friends in chat and contact info, improving user interface clarity.
> Add friend button to chatModal and Enhance friend management class

- app.js
- index.html
- styles.css
- Updated friend status logic in app.js to use numeric values for clarity (0 = Blocked, 1 = Other, 2 = Acquaintance, 3 = Friend).
- Modified index.html to enhance the structure and readability of the friend status radio buttons, including improved accessibility with self-closing input tags.
- Adjusted styles.css to add color coding for friend status options and ensure the update button fits the modal, enhancing the overall user interface.
> Refactor friend status handling and improve UI in FriendModal

- app.js
- Updated the logic in updateContactsList to categorize contacts into four status groups: Blocked, Acquaintances, Friends, and Others, improving clarity and organization.
- Enhanced the rendering process by introducing a helper function for contact items, streamlining the HTML generation for each group.
- Improved sorting and display of contacts, ensuring a more user-friendly interface in the contacts list.
> Refactor contact grouping and rendering in updateContactsList function

- index.html
Updated text in tool form reguarding USD to LIB conversion.
> Updated toll text in toll form.

- app.js
- Introduced NewChatModal class to encapsulate new chat functionalities, enhancing code organization and maintainability.
- Added event listeners for opening, closing, and submitting the new chat form, improving user interaction.
- Removed outdated functions related to chat handling, streamlining the overall structure of app.js.
- Updated existing modal loading logic to include the new chat modal, ensuring a cohesive user experience.
> Implement New Chat Modal class in app.js

- app.js
- Introduced SendModal class to encapsulate send modal functionalities, enhancing code organization and maintainability.
- Replaced direct DOM manipulation with class methods for opening, closing, and submitting the send modal, improving clarity and reducing redundancy.
- Updated event listeners for input validation and balance updates, ensuring a cohesive user experience.
- Removed outdated functions related to the send modal, streamlining the overall structure of app.js.
> Create sendModal class and move related functions and listeners in

- app.js
- Introduced `tollRequiredToReceive` and `tollRequiredToSend` fields in the contact creation process to manage toll requirements effectively.
- Improved error handling in the `updateTollRequired` function to provide clearer warnings when querying contact account data fails, enhancing debugging and user feedback.
> Add missing default toll fields when `createNewContact` and enhance error handling `updateTollRequired()`

- app.js
...and have fallback values where we use parameters.current
fallback being wei * 1n.
> Update `newDataRecord()` to use parameters value from network account 

- app.js
Update logic to account for unit (USD/LIB) for validating balance input in sendModal. Also updating JSDOCs.
- Updated `handleSendAsset` and `refreshSendButtonDisabledState` functions to incorporate balance validation and conversion between LIB and USD based on the current asset symbol.
- Improved user feedback by dynamically updating displayed balance and transaction fee values according to the selected currency, ensuring accurate representation during asset transfers.
> Fix balance validation to account for unit (USD/LIB) and conversion logic

- app.js
The backend was changed, so we need to change the frontend to match.
> change update_chat_toll to update_toll required

- app.js
- **Contact Creation**
- Set new contact’s `timestamp` to `0` instead of current time, ensuring accurate unread message tracking.
- **Toll Required Logic**
- Fix assignment of `tollRequiredToSend` and `tollRequiredToReceive` in `updateTollRequired(address)`:
- Now correctly assigns values based on the user’s and contact’s indices.
- **Chat Read Receipts**
- On closing a chat, automatically send a read transaction if there are unread messages.
- Only send read transactions if the contact is required to pay a toll.
- Add debug logging for read transaction logic and conditions.
---
**Technical Notes:**
- These changes improve message read tracking and ensure toll requirements are correctly handled for both sending and receiving.
> Improve Chat Read Receipts (sendReadTransaction) & Fix Contact Toll Logic (updateTollRequired)

- app.js
- **Toll UI Enhancements**
- In `updateTollAmountUI(address)`:
- Sets the toll value text color to black by default.
- If the user is blocked (`tollRequiredToSend == 2`), sets the toll value color to red and displays "blocked".
- If the chat is free, sets the toll value color to light green for visual feedback.
- **Blocked User Handling in Chat**
- In `ChatModal.handleSendMessage()`:
- Prevents sending messages if the user is blocked (`tollRequiredToSend == 2`).
- Shows a toast notification: "You are blocked by this user".
- Re-enables the send button if blocked.
---
**Technical Notes:**
- These changes improve user feedback and prevent blocked users from sending messages.
> UI Improvements for Toll and Blocked Users in Chat

- app.js
- **Account Creation Robustness**
- Added try-catch block in `handleCreateAccount()` to fetch network parameters before account creation
- Shows warning if network parameter fetch fails but allows account creation to continue
- Prevents account creation from failing due to network connectivity issues
- **Safe Parameter Access**
- Added optional chaining (`?.`) to `parameters.current.defaultToll` and `parameters.current.defaultTollUnit` in `newDataRecord()`
- Prevents runtime errors when `parameters` object is undefined or null
- Ensures fallback values (1 wei for toll, "LIB" for tollUnit) are used when network parameters are unavailable
---
**Technical Notes:**
- These changes improve app resilience when network parameters cannot be fetched during initialization
- Account creation now …
> Improve Network Parameters Error Handling

- app.js
- Updated the structure of failed message handling by renaming properties from handleFailedMessageClick to handleFailedMessageData for clarity.
- Adjusted the logic to ensure proper retrieval and clearing of transaction IDs and message content during retry and delete operations.
- Improved code readability and maintainability by consolidating related functionalities.
> Refactor failed message handling in ChatModal and FailedMessageModal classes

- app.js
- Implemented debounced draft saving to enhance user experience by saving message drafts automatically.
- Added methods to save and load draft messages for the current contact, ensuring drafts persist across sessions.
- Updated input event listener to trigger draft saving while resizing the message input area dynamically.
- Cleared saved drafts upon sending messages to maintain a clean state in the chat interface.
> Add draft message saving and loading functionality in ChatModal class

- app.js
- styles.css
- Updated the showToast function to make the entire toast clickable for closing, enhancing user interaction.
- Adjusted the close button's CSS positioning and added padding to the toast for better layout and usability, ensuring the close button is easily accessible.
> Refactor toast notification behavior and styling

- app.js
...and update calls (#297)
- Added a `friendStatus` parameter to the `createNewContact` function, allowing for customizable friend status when creating a new contact.
- Updated all calls to `createNewContact` throughout `app.js` to include the new `friendStatus` parameter, defaulting to 2 in relevant cases.
- Improved JSDoc comments for better clarity on function parameters and return types.
> Enhance `createNewContact` function with `friendStatus` parameter 

- app.js
…for consistency and improved precision in display (#298)
- Changed formatting for amounts in various functions including updateChatList, updateTollAmountUI, updateWalletView, and updateTransactionHistory to use six decimal places.
- Ensured consistent display of monetary values in the ValidatorStakingModal and ChatModal classes.
- Enhanced user experience by providing more precise financial information in the application.
> Update numeric formatting for monetary values to six decimal place

- app.js
- index.html
- Implemented logic to convert and display asset amounts in USD based on the current balance symbol.
- Updated balance and transaction fee displays to reflect the selected currency, ensuring clarity for users.
- Refactored DOM elements to improve readability and maintainability, including renaming balance symbol elements for consistency.
> Fix: Enhance SendAssetFormModal to support USD display and balance updates

- app.js
- Updated the checkUsernameAvailability function to include a foundAddressObject parameter, allowing for the assignment of the found address when a username is taken.
- Initialized foundAddressObject in SendAssetFormModal to facilitate address updates during username checks, improving user experience and data handling.
> Enhance checkUsernameAvailability function to accept foundAddressObject parameter (#307)

- app.js
- Introduced logic to determine if toll information is needed based on the found address.
- Added a new validateForm method to fetch and store toll details from the network, enhancing the asset sending process.
- Improved code readability by restructuring the checkUsernameAvailability function for better clarity.
> Implement toll information validation in SendAssetFormModal

- app.js
- index.html
- styles.css
- Updated the SendAssetFormModal to include a new UI element for displaying toll information, improving user awareness during asset transactions.
- Implemented the updateMemoTollUI method to dynamically update the toll display based on the required toll information.
- Refactored the toll information retrieval logic to ensure accurate data handling and display, enhancing the overall user experience.
> Enhance toll information display and validation in SendAssetFormModal

- app.js
- index.html
- styles.css
- Removed inline style to ensure the toll memo container is always displayed, enhancing user interaction with the memo feature in the SendAssetFormModal.
> CSS to have default height for empty span

- app.js
- Adjusted spacing in various functions and class properties to maintain consistent formatting.
- Ensured proper use of braces for conditional statements to enhance code clarity.
- Updated comments for better understanding of the code flow.
> Refactor spacing and formatting in SendAssetFormModal and app.js for improved readability

- app.js
- index.html
- Added references for balance and transaction fee elements to streamline DOM access.
- Updated balance and fee display logic to improve clarity and maintain consistency in LIB/USD conversion.
- Refactored the updateBalanceDisplay and refreshSendButtonDisabledState methods for better readability and functionality.
- Improved the handling of balance warnings and validation checks for asset transactions.
> Enhance balance display and fee handling in SendAssetFormModal

- .prettierignore
- .prettierrc
- app.js
- index.html
- styles.css
Will not lint styles.css file when running `npm run format`
- Changed printWidth in .prettierrc from 100 to 120 for better code formatting.
- Refactored multiple event listener assignments in app.js to single-line format for enhanced readability and consistency.
- Cleaned up whitespace in various sections of app.js to improve code clarity without altering functionality.
> Remove styles.css from .prettierignore and increase print-width

- app.js
- Modified the toll calculation in ChatModal to return 0n when the toll required to send is zero, ensuring accurate toll handling.
- This change enhances the robustness of the chat message creation process by preventing unnecessary conversions when tolls are not applicable.
> Update toll conversion logic in ChatModal to handle zero toll cases (#339)

- app.js
- Updated the way the memo input is populated by using optional chaining and a fallback to an empty string, enhancing robustness against undefined values.
- Adjusted the call to handleFailedPaymentClick to ensure it directly references the function, improving clarity and consistency in the code.
> Refactor handleFailedPaymentRetry to improve memo input handling in sendAssetFormModal

- app.js
- removed check for zero amount and adjusted the condition for negative amounts to use BigInt.
- Simplified the total required calculation by directly using the amount instead of a conversion function.
- Updated toll handling in ChatModal to ensure safe checks for zero toll cases, enhancing robustness in balance validation.
> Refactor validateBalance function to use bigInt directly

- app.js
- Added comments in ChatModal to clarify the purpose of toll checks.
- Included a TODO in NewChatModal regarding backend support for updating toll requirements before chat creation, improving code documentation and future development guidance.
> Enhance comments in ChatModal and NewChatModal for clarity on toll handling (#347)

- app.js
PR Summary:
- Added improved error handling for asset transfers and chat messages
- Implemented automatic modal reopening functionality when transactions fail due to toll-related issues
- Added draft message clearing functionality after successful message sending
- Updated JSDoc return types for modal methods to reflect async nature
- Added new `reopen()` methods to both ChatModal and SendAssetFormModal to preserve form values when retrying failed transactions
- Enhanced pending transaction handling to properly manage modal states for failed messages and transfers
Key Changes:
- Added toll-related error detection and automatic modal reopening for failed asset transfers
- Improved chat message error handling with automatic modal reopening for toll-related failures
- Added draft message …
> Refactor ChatModal to improve error handling and UI updates during message and transfer sending (#348)

- app.js
- Updated the processChats function to validate that the username associated with a message matches the sender's address before assigning it to the contact.
- Introduced a new getUsernameAddress function to fetch the address corresponding to a username, improving the accuracy of username handling in chat messages.
- Added error logging for mismatched usernames to aid in debugging and user feedback.
> Enhance username validation in processChats function and add getUsernameAddress utility

- app.js
- Updated the validateBalance function to handle zero amounts, logging a warning and returning false if the amount is zero.
- Improved input handling in SendAssetFormModal by trimming whitespace from the amount input and adding validation for empty amounts, disabling the submit button and clearing warnings accordingly.
- Enhanced user feedback with console warnings for empty or invalid amounts, improving overall user experience.
> Enhance input validation in SendAssetFormModal and validateBalance function

- app.js
- Updated validateBalance to allow zero amounts for messages, removing the check for zero and adjusting the negative amount validation.
- Enhanced input validation in SendAssetFormModal to handle zero amounts, ensuring the submit button is disabled appropriately and warnings are cleared for empty inputs.
- Improved comments for clarity on validation logic, streamlining user feedback and code maintainability.
> Refactor input validation in validateBalance and SendAssetFormModal

- index.html
- styles.css
- Updated the HTML structure of the About Modal to enhance clarity and visual appeal.
- Introduced new CSS classes for better styling and layout management, including sections for content, links, and external resources.
- Improved the overall user experience by making the modal content more accessible and visually distinct.
> Refactor About Modal layout and styles for improved readability and organization

- app.js
This change improves code organization and maintainability by consolidating event listeners and related methods, enhancing the overall clarity of the asset receiving process. Unused functions and event listeners have been removed to streamline the code.
> Refactor receive modal functionality by encapsulating it within a dedicated ReceiveModal class. 

- app.js
- index.html
- Introduced a long polling mechanism to fetch the latest chat data from the server, enhancing real-time chat functionality.
- Updated WebSocket management to ensure initialization only occurs when the wsManager is available, improving stability.
- Adjusted the visibility of the WebSocket status indicator in the UI for better user feedback.
- Enhanced interval management for chat updates and WebSocket indicators to prevent unnecessary operations when not needed.
> Add long polling feature for chat updates and improve WebSocket management

- app.js
This PR fixes an issue where new messages received while the chat tab was hidden would not properly scroll to the newest message when the user returned to the tab.
- **Added message count tracking** when page goes hidden to detect new messages
- **Enhanced `handleVisibilityChange()`** to compare message counts when page becomes visible
- **Triggers chat modal refresh** only when new messages are detected while hidden
- **Replaced `scrollIntoView()` with manual scrolling** using `scrollTop` for better reliability
- **Added modal focus** before scrolling to ensure proper browser behavior
- **Implemented centered scrolling** to position new messages in the middle of the viewport
- **Added visibility state checks** in `processChats()` to prevent unnecessary UI updates when page is hidden
- …
> Fix Chat Modal Scrolling When Returning from Hidden Tab

- app.js
Refactor SignInModal open method in app.js to support asynchronous username handling when recreating a user. Gracefully handle situation where querying unsynced node for account availability that returns `available` though pending create account is successful. Allowing optimistic sign in.
> Refactor signInModal to gracefully handle queuing unsynced validator for account availibility

- app.js
- If currency and amount have not changed, disable the submit button
- when currency is toggled, update the submit button
- when the toll modal is open set the currency toggle to the correct currency
> Set toll should only submit if toll amount has changed

- app.js
- index.html
Enhanced user visibility by adding a new field for Provided Name, hiding unused titles, and ensuring consistent updates for name and subtitle sections.
> Update contact info modal to display Provided Name and adjust name retrieval logic in app.js

- app.js
- index.html
* Adjusted name retrieval logic in app.js to default to 'Not Entered' instead of 'Not provided' for improved clarity.
* Enhanced visibility of contact info fields by conditionally displaying them based on content, ensuring a cleaner user interface.
> Update contact info modal to improve display logic and default values (#391)

- app.js
- index.html
Validator stake form the amount input field is now normalized
> Normalize input amount on stake form

- app.js
Clicking provided name container will fill in name in the editContactModal
> Add click handler for provided name in edit contact modal for improved UI

- index.html
Changed in 3 places:
- My Profile account modal
- Contact Info modal
- Edit Contact info modal (current the X-Twitter field is not visible)
> Replace X with X-Twitter

- app.js
- index.html
- styles.css
* Add a message byte counter to display remaining bytes and validation status.
* Introduce methods to validate message size and update the byte counter based on user input.
* Clear message input and reset UI elements when opening the chat modal.
* Adjust styles for the message byte counter and input layout for better user experience.
> Implement message byte size validation and UI updates in ChatModal

- index.html
- styles.css
Enhance menu item accessibility and styling by adding icons and hover effects in index.html and styles.css. Update menu item layout for improved user experience.
> Add svg icons to menuModal and apply system design styling

- app.js
Simplify event handling and improve username availability checks. Remove deprecated functions and streamline modal interactions for better user experience.
> Refactor create account functionality by encapsulating logic in CreateAccountModal class.

- app.js
Update normalizeName function to include stricter validation and character limits. Enhance documentation for clarity on normalization behavior.
> Add normalization on blur and input for name field in EditContactModal. 

- app.js
Add phone number normalization on blur event in InviteModal and MyProfileModal. Update normalizePhone function to enforce character limits and conditional clearing for improved input validation.
> Blur phone number normalization handling, additional min and max length check in normalizePhone

- app.js
- index.html
- styles.css
Refactor SendAssetFormModal to improve amount handling and display. Update amount calculation for LIB and USD, ensuring correct values are shown in the confirmation modal. Add styling for USD equivalent display in the confirmation modal.
> Refactor SendAssetFormModal to calculate and display USD equivalent of asset amount. 

- app.js
* Introduced HistoryModal class to encapsulate history modal functionality, including loading, opening, and closing the modal.
* Replaced direct DOM manipulation with methods in HistoryModal for better organization and maintainability.
* Updated event listeners and transaction history rendering logic to utilize the new class structure.
* Removed legacy functions related to history modal handling for cleaner code.
> Refactor: Implement HistoryModal class for improved transaction history management

- app.js
- index.html
- styles.css
When preview was overflowing the noti bubble was push out of view. 
- moved noti bubble before the preview
> Fix chat message display in updateChatList function and comment out manifest link in index.html for clarity.

- styles.css
> Enhance contact info modal styles with improved overflow handling and word breaking for better display

- app.js
preventing the following:
1. enter a valid username and amount
2. edit the username to make it invalid 
submit button is enabled while username is being validated
> Disable submit button in SendAssetFormModal during address input to prevent submit without validation

- app.js
• Improve code organization and maintainability by converting the send asset confirmation modal from scattered event listeners and functions into a cohesive class-based structure
• **Extracted `handleSendAsset` function** into a new `SendAssetConfirmModal` class with proper encapsulation
• **Removed global event listeners** for send asset confirmation modal and moved them into the class constructor
• **Added modal loading** in the DOMContentLoaded event listener alongside other modals
• **Refactored DOM element references** to use class properties instead of repeated `document.getElementById()` calls
• **Improved code structure** by grouping related functionality within the modal class
• **Enhanced maintainability** through better separation of concerns and reduced global scope pollution …
> Refactor Send Asset Confirmation Modal into Class-Based Architecture

- app.js
Introduce a new class for the contact search modal, replacing old functions with class methods for better organization and maintainability.
> refactor contact search modal into class

- app.js
- Introduced a ChatsScreen class to encapsulate chat-related functionality, improving code organization and maintainability.
- Updated event listeners and methods to utilize the new ChatsScreen class, enhancing the separation of concerns within the application.
- Removed redundant code related to chat list updates and chat data fetching, streamlining the chat management process.
- Ensured proper handling of chat list UI updates and interactions through the new class structure.
> Refactor Chat Functionality into ChatsScreen Class

- app.js
- Introduced a ContactsScreen class to encapsulate contact-related functionality, improving code organization and maintainability.
- Updated event listeners and methods to utilize the new ContactsScreen class, enhancing the separation of concerns within the application.
- Refactored contact list update logic to streamline UI rendering and interaction handling.
- Removed redundant code related to direct DOM manipulation for contact management, ensuring a cleaner and more efficient implementation.
> Implement ContactsScreen Class

- app.js
- Introduced a WalletScreen class to encapsulate wallet-related functionality, improving code organization and maintainability.
- Updated event listeners and methods to utilize the new WalletScreen class, enhancing separation of concerns within the application.
- Removed redundant code related to direct DOM manipulation for wallet management, ensuring a cleaner and more efficient implementation.
- Enhanced wallet view updates and balance management through class methods, improving overall user experience.
> Refactor Wallet Functionality into WalletScreen Class

- app.js
> Refactor message search modal - cleanup

- app.js
- Improve code organization and maintainability by moving DOM element access and event listener setup into relevant class methods.
- Eliminate duplicate or global event listeners in favor of encapsulated, class-based logic.
- Fix issues with event handler context (`this`) and ensure correct property access.
- **Chat Send Money Button:**  
- Moved the event listener for `chatSendMoneyButton` from the global scope into the `ChatModal` class, specifically within its `load()` method.
- Now uses a class property (`this.chatSendMoneyButton`) and an arrow function to ensure correct context.
- **Password Visibility Toggle:**  
- Moved the event listener for toggling private key visibility from the global scope into the `CreateAccountModal` class constructor.
- …
> Refactor Modal Event Listeners and Move DOM Access to Class Methods

- app.js
Deleting function that was replaced in #469
> delete replaced qr function

- app.js
- styles.css
This PR adds fullscreen functionality to the Liberdus web app, specifically targeting mobile browsers that support the Fullscreen API (primarily Android Chrome). The implementation provides a seamless fullscreen experience when users interact with the app, while maintaining proper safe area handling and responsive design.
- **Added fullscreen detection**: Event listeners for `fullscreenchange` to detect when the app enters/exits fullscreen mode
- **Mobile detection**: Added `isMobile()` function to identify mobile devices (excluding iOS since Fullscreen API is not supported)
- **Fullscreen triggers**: Added `enterFullscreen()` calls to key user interactions:
- Sign In button click
- Menu modal open/close
- Create Account modal open
- **CSS class management**: Automatically adds/removes …
> Add Fullscreen Support for Mobile Browsers

- styles.css
> Remove margin-top from small elements in styles.css to enhance layout  spacing.

- app.js
- index.html
- styles.css
This PR improves the account backup functionality by adding clear user guidance and implementing conditional export logic based on user authentication state.
**UI/UX Improvements:**
- Added descriptive text to the export modal explaining what the backup does and when it applies
- Styled the new description text to match the system design using consistent typography and spacing
**Backup Logic Enhancement:**
- Refactored export functionality to handle two scenarios:
- `handleSubmitOne()`: Exports current account when user is signed in
- `handleSubmitAll()`: Exports all accounts when user is not signed in
- Updated form submission handler to conditionally call appropriate export method based on `myData` availability
**Infrastructure Updates:**
- Updated network configuration to use …
> Enhanced Account Backup Modal with Conditional Export Logic

- app.js
- index.html
- styles.css
> Update contact menu item to 'Help' and change associated icon to GitHub in index.html and styles.css

- app.js
- index.html
- network.js
- styles.css
- Introduced a toggle for developer options in the UI, allowing users to enable or disable string substitution.
- Added event listeners for handling string selection and custom input for old and new strings.
- Implemented mutual exclusion logic between dropdowns and custom inputs to prevent conflicting selections.
- Enhanced the modal's form handling to include clearing and resetting fields when toggling developer options.
- Updated styles for the new developer options section to improve user experience.
> Add developer options to RestoreAccountModal for enhanced string substitution functionality

- app.js
- network.js
- network.js_loc
- network.js_web
- Implemented file input listeners in RestoreAccountModal to extract netids from a selected file and populate dropdowns.
- Added logic to handle encrypted files and parse netids from localStorage keys.
- Updated network.js, network.js_loc, and network.js_web to change gateway URLs to secure connections and added an old netid for reference.
> Add netid extraction functionality to RestoreAccountModal and update network configurations

- app.js
- index.html
- styles.css
- Updated CreateAccountModal to display a section for migrating accounts when there are mismatched network IDs.
- Enhanced the UI in index.html for the migrate accounts section, including updated labels and button styles for better user experience.
- Added new styles in styles.css for the migrate accounts modal to improve visual consistency and usability.
> Add dynamic logic for migrate button in createAccountModal

- app.js
- index.html
- styles.css
- Implemented a new Migrate Accounts modal to facilitate the migration of accounts between networks, preserving user data.
- Enhanced the UI in index.html to support account selection via checkboxes, improving user experience during the migration process.
- Added necessary JavaScript functions for handling account migration logic, including validation and updating the accounts registry.
- Updated styles in styles.css to ensure a consistent and user-friendly design for the migration modal.
> Show list of migrable accounts in MigrateModal

- app.js
- Simplified string substitution in RestoreAccountModal by removing match count checks and feedback logs, streamlining the process.
- Enhanced MigrateAccountsModal to include decryption of file content if necessary, ensuring data integrity during migration.
- Updated accounts registry handling to retrieve account addresses directly from the registry instead of localStorage, improving efficiency.
- Added success feedback via toast notifications and implemented a page reload after migration completion for better user experience.
> Refactor account migration logic in MigrateAccountsModal and RestoreAccountModal

- app.js
- Enhanced offline functionality by removing unreliable `checkOnlineStatus()` function
- Improved network request handling to prevent unnecessary API calls when offline
- Added proper offline state checks across multiple functions
**Core Changes:**
- **Removed `checkOnlineStatus()` function** - This function was unreliable and has been replaced with the global `isOnline` state variable
- **Updated network request functions** to use `isOnline` instead of making HEAD requests to check connectivity
**Function Updates:**
- **`queryNetwork()`** - Now uses `isOnline` state instead of `checkOnlineStatus()`
- **`getSystemNotice()`** - Added offline check to prevent unnecessary network requests
- **`longPoll()`** - Added offline check to skip polling when not connected
- …
> Improve Offline Detection and Network Handling

- app.js
- **Changes made:**
- Added JavaScript confirmation dialog before global account restore to warn users about data loss
- Enhanced user experience by providing clear warnings and allowing users to cancel destructive operations
The key improvement is the confirmation dialog that prevents accidental data loss during multi-account restores.
> Improve user safety during multi-account restoration

- app.js
- Removed the WebSocket manager and related logic, including connection initialization, subscription checks, and disconnection handling.
- Updated polling logic to rely on the useLongPolling flag, streamlining the code and enhancing maintainability.
- Cleaned up commented-out code and unnecessary variables related to WebSocket management, improving overall readability.
> Deprecate WebSocket Class in app.js

- app.js
- Updated the logic for storing user data in localStorage to encrypt the data if a lock encryption key exists, improving security during account restoration.
- Ensured that the data is stored in an encrypted format when the app is locked, enhancing user data protection.
> Enhance data storage in RestoreAccountModal to support encryption when app is locked

- app.js
- Improved error handling for transaction injection by checking if the error is a string.
- Updated the submit button event listener to trigger on click instead of submit.
- Implemented a new migration process for accounts, including initialization of temporary data structures.
- Added asynchronous processing for account migration with success and failure tracking.
- Introduced functions to handle individual account processing and migration, including registration and data migration.
- Enhanced user feedback with loading toasts and results display after migration completion.
> feat: Enhance account migration process in MigrateAccountsModal

- app.js
> Reset myAccount and myData to null in CreateAccountModal to ensure proper state management after account actions.

- app.js
- Change return type of populateAccounts method to Promise<void> for better async handling.
- Disable submit and back button during account processing to prevent multiple submissions.
- Re-enable submit button after processing completes to enhance user experience.
> Update MigrateAccountsModal to disable submit and back button during submission

- app.js
- Changed updateTransactionHistory and handleAssetChange methods to synchronous to improve performance and simplify code structure.
- Ensured that the transaction history updates are handled without awaiting, as the operations do not require asynchronous handling.
> Refactor HistoryModal: Remove async from updateTransactionHistory and handleAssetChange methods

- app.js
- encryption.worker.js
After attached file is encrypted it is uploaded and the download url is added to the fileAttachments array
> Upload file attachment

- app.js
Implement functionality to unsubscribe from push notifications when the document visibility changes to visible.
> Unsubscribe from notifications on visibility change

- app.js
- unsubscribe now only unsubscribes the current account
- sign out triggers subscribe all acounts
- sign in triggers unsubscribe
- on dom load subscribe
> Unsubscribe only logged in account

- app.js
- index.html
- styles.css
-Shortened warning texts for node address and stake amount, changing display styles to 'inline'.
-Enhanced HTML structure to include warning spans directly in labels for better user feedback.
-Adjusted CSS to ensure proper styling for new warning elements.
> Update validation messages and styles in StakeValidatorModal.

- app.js
- index.html
-Updated balance warning messages to differentiate between insufficient balance and fees.
-Refactored balance display to show available balance and transaction fee in a structured format.
-Added a new method to update balance and fee dynamically based on network parameters.
> Enhance balance validation and display in StakeValidatorModal.

- app.js
- index.html
- styles.css
- Improves user experience by replacing modal dialogs with context menus for failed message actions
- Reduces UI clutter and provides more intuitive interaction patterns
- Eliminates code duplication by creating shared positioning utilities
- **Replaced FailedMessageModal class with FailedMessageMenu class** - Converted from modal-based to context menu-based interaction
- **Created shared positioning utility** - Extracted `positionContextMenu()` function to eliminate duplicate positioning logic between message context menus
- **Updated message click handling** - Modified `handleMessageClick()` to directly call `failedMessageMenu.open()` instead of the old modal approach
- **Simplified retry mechanism** - Removed stored state management in favor of …
> Replace Failed Message Modal with Context Menu for Better UX

- app.js
when in the native app clicking attachment link will post a message to trigger the download
related native app PR https://github.com/Liberdus/liberdus-native-app/pull/1
> Implement file download handling for React Native

- app.js
Improve user experience by allowing viewable file attachments to open directly in browser tabs while maintaining download functionality.
- **Added file type detection** - New `isViewableInBrowser()` method to identify browser-compatible file types (images, PDFs, text, videos, audio, JSON, XML)
- **Implemented dual functionality** - Viewable files now open in new tab AND download simultaneously
- **Enhanced download helper** - New `triggerFileDownload()` method with proper JSDoc documentation
- **Improved memory management** - Consolidated blob URL cleanup using try/finally block with 2-second timeout
- **Better error handling** - Graceful fallback to download-only when popup blockers prevent new tab opening
- **Code documentation** - Added comprehensive JSDoc comments for new methods
- …
> Enhanced File Attachment downloading with Browser Preview

- app.js
- on attaching file loading toast is now removed after the file upload is complete or on error
- added `Decrypting attachment` loading toast on clicking attachment link
- removed unnecessary .catch on handleAttachmentDownload since it handles its own exceptions
> Fix loading toast for attaching and downloading files

- app.js
- index.html
when there is a lock first show change or remove password buttons. Once an option is selected the relavent fields will be displayed
> Add modes to lock modal for password management

- app.js
- index.html
- styles.css
- Changed the warning message element to use CSS classes for visibility instead of inline styles.
- Updated styles to reserve space for the warning message and added transition effects for smoother visibility changes.
- Adjusted margins in the toll modal for better layout consistency.
> Refactor warning message display in TollModal for improved UX

- app.js
Enhance state persistence and lifecycle management when the app runs in a React Native WebView environment, particularly for force-close scenarios where standard web events may not reliably fire.
- **Added ReactNativeApp class** to handle WebView communication with the React Native wrapper
- **Implemented message listener** for background state changes from React Native
- **Enhanced state saving** when app goes into background via both web events and React Native messages
- **Improved chat message count preservation** during app backgrounding
- **Added dual-layer state management** for better reliability in WebView environments
The implementation provides a more robust solution for maintaining app state when users force-close the app by swiping it away from the recent apps screen, …
> Add React Native app integration and state management enhancements

- app.js
- Implement automatic localStorage monitoring to prevent storage-related issues
- Provide user warnings when storage is critically low (< 100KB available)
- Add comprehensive storage analytics for debugging and monitoring
**🔧 New LocalStorageMonitor Class:**
- **`findLocalStorageLimit()`** - Binary search algorithm to precisely determine localStorage capacity
- **`getLocalStorageUsage()`** - Calculate current storage usage with UTF-16 encoding support
- **`getStorageInfo()`** - Comprehensive storage report with limit, usage, available space, and percentage
- **`checkStorageOnStartup()`** - Automatic storage check with console logging and user warnings
**📊 Integration:**
- Added `localStorageMonitor.load()` to DOMContentLoaded event for automatic startup monitoring
- 100KB warning …
> Add localStorage monitoring with automatic startup checks and low storage warnings

- app.js
• Improve mobile user experience by adding keyboard handling for React Native WebView integration
• Clean up codebase by removing unused polling function
• **Added `adjustForKeyboard()` function** - Implements visual viewport handling to dynamically adjust app container height when mobile keyboard appears/disappears
• **Added CSS custom property support** - Uses `--viewport-height` property to maintain proper layout during keyboard interactions
• **Integrated keyboard adjustment** - Called during app initialization to enable responsive mobile layout
• **Removed `pollChatInterval()` function** - Eliminated unused polling interval function that was no longer needed
• **Enhanced mobile compatibility** - Added toast notifications and console logging for …
> Add React Native WebView keyboard adjustment and remove unused polling function

- app.js
- index.html
- styles.css
- **Prevents data loss** when users check for app updates
- **Guides users to backup first** before potentially risky app store interactions
- **Improves user safety** with clear warnings about uninstall risks
**🔧 New Modal System:**
- Created `UpdateWarningModal` class with proper event handling
- Added modal HTML structure with warning content and action buttons
- Integrated with existing `backupAccountModal` for seamless backup flow
**🎨 Enhanced UX:**
- **Red "Continue to App Store" button** to emphasize danger
- **Green "Backup My Data First" button** as recommended safe action
- **Clear warning text** about data loss risks during app updates
- **Proper button ordering** (dangerous action first, safe action second)
**💻 Technical Implementation:**
- Added dedicated CSS styling for …
> Add Update Warning Modal with Data Backup Protection

- app.js
- Eliminated the `pollChatInterval`, `pollChats`, and `scheduleNextPoll` functions to streamline chat polling logic.
- Removed unused variables `ecSharedKey`, `pqSharedKey`, `deriveDhKey`, and polling interval constants for improved code clarity.
- Updated message handling in `SearchMessagesModal` by removing unused `index` variable
> Refactor app.js: Remove unused polling functions and clean up imports

- app.js
- index.html
- styles.css
- rename all instances of export to backup
- if password is used require confirmation password
> Rename export to backup

- app.js
- index.html
* Introduced a new launch section in the Create Account Modal with a button to open the launch modal.
* Moved the launch modal ordering in html
* The launch section is conditionally displayed for React Native WebView environments.
> Add launch button to Create Account Modal for RN

- app.js
> In the migrate modal sort accounts by netid then username

- app.js
Extended ReactNativeClass to support keyboard/viewport -related data communication
> Added correct keyboard height detection through web view communication

- app.js
- The Welcome screen was experiencing lag during startup due to expensive localStorage capacity calculations
- The `findLocalStorageAvailable()` method performs a binary search testing up to 6MB of data on every app startup
- This calculation was blocking the UI thread and causing noticeable delays
- **Added localStorage capacity caching mechanism** - Store calculated capacity in localStorage to avoid recalculation
- **Modified `getStorageInfo()` method** - Now uses cached capacity instead of running expensive binary search on every startup
- **Added `getCachedOrCalculateCapacity()` method** - Checks for cached value first, only calculates once on first visit
- **Added `CAPACITY_KEY` constant** - Defines the localStorage key for storing capacity data
- **First startup**: Still performs …
> Optimize localStorage capacity calculation with caching to improve Welcome screen performance

- app.js
Unsubscribe if we are signed in when app resumes by receiving foreground native app event
> Add handling for foreground data type in ReactNativeApp class to manage app state subscriptions

- app.js
- index.html
- **Reason for PR**: Display the React Native app version on the welcome screen to provide users with version information
- **Changes Made**:
- Added app version display element to welcome screen HTML with proper styling
- Extended WelcomeScreen class with app version handling functionality
- Modified ReactNativeApp class to store and communicate app version to welcome screen
- Implemented automatic app version display when received from React Native bridge
- Added fallback check for existing app version when welcome screen loads
The implementation cleanly integrates the app version display underneath the existing version information, showing "App Version: [version]" when available from the React Native app.
> Add App Version Display to Welcome Screen

- app.js
Add isActive method to SignInModal and update ReactNativeApp to refresh modal state. 
This enhances user experience by ensuring the sign-in modal list reflects that account that received the notfication   by reflecting it at the top of the list with an emoji.
> Handle notification click that resumes on signin modal

- app.js
adds save state in 3 locations:
- UpdateChatData if > 0 chats received
- injectTx 
- checkPendingTransactions is transactions were processed
> Save state after msg retrieval and txn processing

- app.js
Simplified the logic to get the device and expo tokens from the window since they are no longer added to the query params
> Pull device and push token from window

- app.js
- index.html
- styles.css
Add a "Backup all accounts" checkbox to the backup modal that allows signed-in users to choose between backing up just the current account or all accounts.
- Updated description text to clarify user choice: "If you are signed in you can choose to backup all accounts or just the signed in account."
- Added checkbox form group above password field with proper structure
- Hidden by default with `style="display: none;"`
- **Enhanced `load()` method**: Added references to checkbox elements
- **Updated `open()` method**: 
- Shows checkbox when user is signed in (`myData` exists)
- Hides checkbox when user is not signed in
- Sets appropriate default states (unchecked for signed-in, checked for not signed-in)
- **Modified form submission**: Replaced direct method calls with new `handleSubmit()` …
> Add Backup All Accounts Checkbox to Backup Modal

- app.js
updates the following functions to use the new getStabilityFactor function:
- ValidatorStakingModal
- updateTollAmountUI
- updateMemoTollUI
- validateToll
> use getStabilityFactor 

- app.js
- index.html
- styles.css
**Reason for PR:** Improve code maintainability and reduce CSS bloat by removing unused styles and consolidating patterns.
- **Removed unused CSS classes and IDs** (ws-status-indicator, scan-highlight, logs-container, dropdown-menu, etc.)
- **Consolidated form patterns** using modifier classes (`form--narrow`, `form-actions`) instead of modal-specific rules
- **Added wrapper divs** with `form-actions` class around submit buttons for consistent spacing and layout
- **Introduced CSS design tokens** (variables) for colors, shadows, and spacing to improve consistency
- **Refactored HTML structure** to use new form component system with consistent wrapper divs
- **Fixed button styling consistency** across modals to reuse shared `.btn` patterns
- **Improved floating button** …
> CSS Refactoring for Maintainability and Cleanup

- app.js
- index.html
Adds estimated rewards to the Validator Staking modal
> Add estimated rewards to ValidatorStakingModal

- app.js
- index.html
Rename the StakeInfo modal to Farm
> Rename stakeInfo to farm

- app.js
Transform the transfer memo field into a JSON object before encryption.
Merge AFTER #702
> Encode transfer memo as JSON object

- app.js
- index.html
- styles.css
Introduce a call button in the chat modal that allows users to initiate a Jitsi video call. The implementation includes generating a unique Jitsi link and sending it as a call message to the contact.
> Add call button to chat modal for Jitsi calls

- app.js
- index.html
- styles.css
- Adds voice message button next to the send chat button
- Opens a modal allowing the user to record, playback, and send an audio message
- Audio messages are encrypted and uploaded like attachments and sent as a message
- In the chat a audio message can be played to listen to it. In the background each time it is played the message is downloaded into memory and decrypted then played.
> Add voice messaging feature

- app.js
Refactor handleSubmit in LaunchModal to use async/await for improved error handling and logging during network.js validation
> Fix launch URL handleSubmit fetch by using async/await

- app.js
- styles.css
Enhance SendAssetFormModal: Clear amount input on focus if it contains "0" for better user experience. 
Update styles for amount container to improve spacing and restore right border for input field.
> Enhance `SendAssetFormModal` focus when value is 0 and spacing between input and button for amount field

- app.js
- Refactor URL parsing, fetching, and response handling into distinct steps for clarity.
- Improve error logging for URL parsing, fetch failures, and response validation.
- Ensure user feedback through toast notifications for various error scenarios.
- Validate required properties in the network.js response more robustly.
> Revert handleSubmit fetch problem for launch modal with multiple try catches

- app.js
Remove keyboard adjustment functionality for React Native WebView from app.js to streamline code and improve clarity.
> Remove commented out keyboard adjustment function

- app.js
- index.html
- styles.css
Enhance username availability checking in MigrateAccountsModal by adding error handling and rendering for inconsistent accounts. Update app.js and index.html to support new error section, and adjust styles for improved layout and visibility of warning messages.
> Move rendering of inconsistent and error list of migrate modal below submit button

- app.js
Moved and renamed `getAvailableUsernames `function to `getSignInUsernames`.Iintegrated username retrieval into the SignInModal class. Updated welcome screen logic to utilize the new method for checking available usernames, enhancing code clarity and maintainability.
> Refactor: Rename `getAvailableUsernames`, move into signInModal, and reuse

- app.js
- data_structures_flow/search/chat-search-flow.md
- data_structures_flow/search/contacts-search-flow.md
- lib.js
Refactor identicon generation in app.js and lib.js by removing unnecessary async/await usage, improving performance and code clarity. 
Update related functions in chat and contact search flows to reflect these changes.
Remove commented out code.
> Code audit 11, 15: make identicon generation synchronous and remove commented out code

- app.js
- index.html
- styles.css
Refactor empty state handling in app.js and index.html to improve UI clarity. Replace inline HTML for empty states with CSS display toggling for better maintainability. Update styles.css to enhance empty state presentation across various screens.
> Audit refactor: Use relevant class .open in `switchView` and move `empty-state` inline CSS into `styles.css` file and html into index.html.

- app.js
Implement new methods to manage the visibility of the `new chat button` in the `Footer` class. 
Update view switching logic to utilize these methods for improved clarity. 
Adjust memo preview length in `ChatsScreen` for better display of messages. 
Refactor username display in `getContactDisplayName` function for consistency.
> Audit refactor: `handleSignOut` and `updateContactList` new methods and switchView logic improvement

- app.js
Have MenuModal class and SettingsModal class after the WalletScreen class so WalletScreen is next to ChatsScreen and ContactsScreen
> Rearrange order of classes

- app.js
Refactor balance fetching logic in WalletScreen to handle errors more gracefully. 
Remove commented-out code and improve clarity by ensuring balance updates only occur when data is valid. 
Display a toast notification for failed balance retrieval attempts.
> Audit Refactor: Handle updateWalletBalance query error

- app.js
**Reason for PR:** Performance optimization and code maintainability improvements for the username selection dropdown.
**Changes made:**
- **Performance:** Convert notification address lookups from O(n) `includes()` to O(1) `Set.has()` operations
- **Algorithm:** Replace inefficient filter/unshift loop with single stable partition pass for username sorting
- **Eliminate redundancy:** Precompute notification status map to avoid repeated address lookups during rendering
- **Safety:** Add null-safety guards for missing usernames/netid data with proper fallbacks
- **Maintainability:** Improve code readability with explicit partitioning logic and clearer variable names
The optimizations provide significant performance improvements for users with many accounts while maintaining identical UI …
> Optimize `updateUsernameSelect()` performance with Set-based lookups and stable partitioning

- app.js
- Updated the open method to conditionally display the modal based on local storage lock status, improving user experience.
- Refactored the unlock modal logic to ensure proper handling of button clicks after unlocking, enhancing interaction flow.
- Improved code clarity by consolidating button click handling and ensuring the unlock modal closes before triggering subsequent actions.
> Enhance Welcome Menu Modal lock functionality in app.js

- app.js
- styles.css
Update toast notification for toll information in ChatModal to use 'toll' class for improved styling and clarity. 
Added corresponding CSS styles for 'toll' to maintain consistent visual presentation.
> Fix: Toll toast to have it's own CSS class to not affect center align of info toast

- meet/index.html
fixes for mobile
- footer no longer hidden
- max 2 wide video grid
- participants panel hidden
> Mobile friendly meet page

- app.js
- Implemented synchronous eligibility checks based on cached contact data when attempting to call a user.
- Added toast notifications to inform users if they are blocked or need to be added as a friend before making a call.
- Enhanced user feedback and clarity regarding calling restrictions based on contact status.
> Add eligibility checks for calling users in handleCallUser method

- app.js
• **Added `formatTollDisplay()` method** - Centralized toll formatting logic with proper USD/LIB conversion and error handling
• **Enhanced offline support** - Added explicit offline state detection and graceful fallback when no cached toll data exists
• **Improved error handling** - Added null checks and safe fallbacks for missing contact data
• **Simplified `updateTollAmountUI()`** - Refactored to use the new formatting method, reducing code duplication
• **Fixed `updateTollValue()`** - Added proper network data validation before processing toll updates
• **Commented out debug log** - Removed verbose keyboard detection logging
Improves toll display reliability and user experience by handling offline scenarios gracefully, centralizing formatting logic, and adding robust error handling …
> Refactor ChatModal Toll Display Logic and Improve Offline Handling

- app.js
Adds ability to edit the memos of payment messages that you send.
> Edit chat message memos 

- app.js
- lib.js
Updates transaction fees and stability factor to use the new string version of the network params. Also adds the EthNum utility class to the lib.
> Use new string network params

- app.js
• **Removed verbose debug logs** - Eliminated 15+ `logsModal.log` statements that were cluttering output with detailed URL validation, fetch errors, and React Native message handling
• **Added storage monitoring on sign-in** - Now logs localStorage usage, availability, and percentage used every time a user successfully signs in
• **Streamlined notification logging** - Kept essential notification flow logs while removing redundant debug messages
• **Maintained critical operational logs** - Preserved important logs for version tracking, user sessions, and mobile app integration
• **Reduce log noise** - Clean up development/debug logs that were making production logs hard to read
• **Improve monitoring** - Add storage usage tracking to help identify potential storage issues early
• **Better …
> Clean up debug logging and add storage monitoring logsModal log

- app.js
- index.html
- styles.css
Added real-time ticking clocks to modal headers to provide users with current time awareness when viewing scheduled calls and scheduling new calls.
• **HTML Structure**: Added current time display elements to Calls Modal and Call Schedule Date Modal headers
• **CSS Styling**: Created responsive `.current-time` class with consistent design patterns
• **JavaScript Implementation**: 
- Created reusable `ClockTimer` utility class to eliminate code duplication
- Integrated timer lifecycle management with modal open/close events
- Used existing time infrastructure (`getCorrectedTimestamp()`, `timeSkew`) for accuracy
• **Time Format**: 12-hour format with AM/PM indicators for user-friendly display
• **Real-time Updates**: Clock ticks every second showing current time
• **Automatic Lifecycle**: …
> Add Ticking Clock to Modal Headers of callScheduleModal and callsModal

- app.js
- Fix password validation logic to prevent form submission when passwords don't match
- Improve button state management to prevent users from bypassing validation
- Optimize user experience with faster input validation
- **Password validation**: Moved password matching check to beginning of form submission to catch mismatches early
- **Button state**: Keep submit button disabled when passwords don't match, preventing invalid submissions
- **Loading toast**: Moved loading toast after password validation to avoid showing it unnecessarily
- **Performance**: Reduced debounce delay from 250ms to 100ms for faster input validation feedback
- **Error handling**: Streamlined error handling flow and removed redundant button re-enabling code
- **Code cleanup**: …
> UnlockModal: Fix Password Validation and Button State Management

- app.js
**Problem:**
- On Android, new messages received while app was in background weren't being appended to active chat modal when user resumed the app
- iPhone worked correctly, but Android required closing/reopening chat to see new messages
**Root Cause:**
- Android fires multiple background events while app is sleeping, causing `lastMessageCount` to be overwritten with updated message count
- On resume, `currentCount` matched `lastMessageCount`, so append logic didn't trigger
**Solution:**
- Modified `lastMessageCount` to act as a one-time snapshot during background sessions
- Initialize as `null`, set only once when going to background, compare on resume, then clear
- Prevents Android's multiple background events from overwriting the original count
**Changes:**
- Initialize …
> Fix Android chat message not appending on app resume

- app.js
Rename unschedule call to match the message name in native app https://github.com/Liberdus/liberdus-native-app/commit/6936f0a79548a13788b0b2d940c52876e6f559af
> Rename sendUnscheduledCall to sendCancelScheduledCall

- app.js
- Prevent call invites from being sent to users who haven't added the sender as a friend or connection
- Align call invite behavior with existing call functionality that already enforces this requirement
- **Call Invite Gating**: Added toll requirement check in `CallInviteModal.sendInvites()` that queries `/messages/{chatId}/toll` per recipient
- **Blocked Users**: Skip sending invites to blocked users (tollRequiredToSend === 2) with warning toast
- **Non-Friends**: Skip sending invites to users who haven't added sender as friend/connection (tollRequiredToSend === 1) with instructional toast
- **Null Safety**: Added null-safety to toll query with `chatIdAccount?.toll?.required?.[toIndex] ?? 1`
- **Toast Cleanup**: Removed unused parameters from …
> Enforce Friend/Connection Requirement for Call Invites

- app.js
Clears notifications for the current address when signing out
> Clear notification on signout

- app.js
- index.html
- network.js
- styles.css
**Purpose:** Enable automatic detection and user notification when native app updates are available.
**Changes:**
- **Added version checking system** in `ReactNativeApp` class:
- `checkAppVersionUpdate()` - compares native app version with required version from network config
- `compareVersions()` - handles YYYY.MMDD.HHmm format version comparison
- `showUpdateNotification()` - displays styled toast with platform-specific store links
- **Added app version requirements** in `network.js`:
- Separate `app_version` config for iOS and Android platforms
- Format: `YYYY.MMDD.HHmm` (e.g., "2025.0916.1621")
- **Integrated version check** into existing app flow:
- Triggers automatically when native app sends `APP_PARAMS` with `appVersion`
- Only shows notification on welcome screen when update is …
> Add Native App Version Update Notifications

- app.js
Implement a check to ensure that the password and confirmation password match before allowing the backup submit to proceed.
> Backup Modal enforces password confirmation match on submit

- index.html
- styles.css
- Enhance toll display UI with informational icon for better user experience
- Added info icon after toll amount display in message input area
- Created reusable `--icon-info` CSS variable following existing icon pattern
- Implemented proper vertical alignment and hover effects for the icon
- Updated existing menu item to use new CSS variable for consistency
- Added responsive styling with opacity transitions and cursor pointer
**Files Modified:**
- `index.html` - Added toll info icon span element
- `styles.css` - Added CSS variable, icon styling, and alignment fixes
> Add Info Icon to Toll Display

- app.js
Refactor friend status handling in FriendModal to streamline friendOld status storage. 
Update checkPendingTransactions to refresh contact list upon status revert.
> Fix when user changes between friend and connection so we don't think there is a pending tx

- app.js
- Adds balance check to video call before opening the call schedule modal
- Adds balance check to voice message before opening the voice recoding modal
- Adds balance check before sending delete for all message
- Change "Insufficient balance for fee and toll" toast message on standard messages to dynamically add "and toll" to the end of it only when a toll is not 0
> Validate balance check for call, voice message, and delete for all

- app.js
- Clean up codebase by removing redundant code, commented-out lines, and unnecessary comments
- Improve code readability and maintainability
- **Friend Modal**: Removed optional chaining operator (`?.`) from `contact?.friend.toString()` to `contact.friend.toString()` since contact is already validated
- **Asset Price Updates**: Removed commented-out code lines for `asset.lastPriceUpdate` and asset array update
- **Network Query**: Removed TODO comment about showing offline status to user
- **Chat Processing**: Removed TODO comment about checking if sender processing is working
**Impact:**
- Cleaner, more maintainable codebase
- No functional changes to application behavior
- Improved code readability by removing dead code and outdated comments
> Code Cleanup: Remove Unnecessary Code and Comments

- app.js
- index.html
- styles.css
- Adds a QR code to the MyInfo modal which contains the username
- Adds QR upload and scanning to the New Chat modal which will fill in the username field
> Add username QR to myInfo and qr scan to NewChat

- index.html
When no value present then label will not appear unless value is present like the other labels in myInfoModal
> Update contact info item in index.html to be initially hidden 

- app.js
- index.html
- Add a Source modal with links to github and source files
- Add link to the Source modal inside the about modal
- remove source file links from the about modal
> Add Source Modal

- app.js
Replace call timestamp comparison with existing helper methods
- isCallExpired() method which checks if more than 2 hours have elapsed since call start
- isFutureCall() method
> Update scheduled call logic for React Native

- app.js
Switches from the single notificationAddresses list of addresses in local storage to an a `notifications` item which separates addresses with notifications by network and includes the last notification timestamp
localStore('notifications') =
{ 
'netid1': 
{
'timestamp': 123,
'addresses': [ addr1, addr2 ]
}
'netid2':
{
'timestamp': 123,
'addresses': [ addr1, addr2 ]
}
}
When processing ALL_NOTIFICATIONS_IN_PANEL addresses notifications already processed (timestamp not newer than stored timestamp) will not get saved in local store. 
Also impliments the updated clear notification message when an address has read all its messages we no clear the notifications for that user on the react native side
> Implement per network notification structure with latest timestamp tracking

- app.js
Ensure the toast type reflects the success or error status when submitting friend changes.
> Set appropriate toast type on friend submission

- app.js
- styles.css
Enhance touch move blocker to allow vertical panning within form container in addition to message input and messages container; update button padding in styles.css for improved layout.
> Allow forms to scroll when keyboard is up

- app.js
Enhance the readability and maintainability of the code that manages the display of profile fields based on their values. Adjustments include clearer variable names and comments to better explain the logic for showing or hiding elements.
no logic changes, simply making the code clearer.
> Improve clarity of updateMyInfo field handling

- app.js
* Implement logic to retrieve and use cached network parameters when offline.
* Add error handling for parsing cached data and log appropriate messages.
* Cache fetched network parameters for future offline use.
> Add offline caching for network parameters in getNetworkParams function

- app.js
Enhance FriendModal submit button logic to disable when contact is not found or offline; update markConnectivityDependentElements to include friend status input.
> Fix offline handling of friendModal's submit and radio buttons

- app.js
Implement handleExternalClick method to check internet connectivity before opening new pages, displaying a warning toast if offline.
> Refactor external link handling in MenuModal to improve offline user experience
