- app.js
- styles.css
- Implemented visual notification indicators for the Chats and Wallet tabs when new messages or transfers are received while not on the respective screens.
- Updated CSS to style the notification indicators and ensure they appear correctly when the 'has-notification' class is applied.
> Add notification indicators for chat and wallet tabs

- app.js
- Update contact information display to truncate long addresses for better readability in chat list.
- Remove error causing `await` in closeChatModal function for improved performance.
> Refactor contact display in chat list to truncate long addresses (#49)

- index.html
Problem: `newChatModal` z-index was not higher than `contactsScreen`
Solution: Moved the `newChatModal` z-index down the list in index.html to be after contactsScreen so it has a higher z-index
> `newChatModal` z-index fix when clicking `newChatButton` from `contactsScreen`

- app.js
This error occurred because the `closeSendModal` function was attempting to reset a property on a non-existent object `opensendModal` (with lowercase 's').
The codebase consistently uses `openSendModal` (with capital 'S') as both a function and an object with properties:
1. As a function, it opens the send modal UI
2. As an object, it stores state through the property `openSendModal.username`
However, in the `closeSendModal` function, this was incorrectly referenced as `opensendModal.username` (lowercase 's'), causing a ReferenceError since that object doesn't exist.
```diff
async function closeSendModal() {
await updateChatList()
document.getElementById('sendModal').classList.remove('active');
document.getElementById('sendForm').reset();
-   opensendModal.username = null
+ …
```
> Reference Error while calling openSendModal

- app.js
- lib.js
- styles.css
feat: Make URLs in chat messages clickable links
This PR implements the functionality to automatically detect and convert URLs starting with `http://` or `https://` within chat messages into clickable HTML links.
Changes:
- Added a `linkifyUrls` utility function to `lib.js` that identifies URLs **explicitly starting with `http://` or `https://`** and wraps them in `<a>` tags. URLs starting with `ftp://`, `file://`, or `www.` without a protocol prefix are no longer converted.
- Updated `openChatModal` and `appendChatModal` in `app.js` to use `linkifyUrls` when rendering message content.
- Added CSS rules in `styles.css` to style the links for better visibility:
- Links in sent (blue) messages are now white and underlined.
- Links in received (grey) messages are now underlined.
Outcome: …
> Make URLs in chat messages clickable links

- app.js
- index.html
- styles.css
**feat: Add Private Key Visibility Toggle**
This PR implements a visibility toggle for the "Private Key" field on the "Create Account" modal.
*   **HTML (`index.html`):** Changed the input type to `password` and added a `<button>` element for the toggle.
*   **CSS (`styles.css`):** Styled the toggle button using URL-encoded SVG background images for eye/eye-slash icons, positioning it within the input field. Handled default, toggled, and hover states. Added right padding to the input field.
*   **JavaScript (`app.js`):** Added a click listener to the toggle button that swaps the input field's `type` between `password` and `text` and toggles a CSS class on the button to update the icon.
> Add Private Key Visibility Toggle

- app.js
- index.html
- styles.css
This PR refactors the QR code functionality in the "Receive" modal:
1.  **Removes QR Data Preview:** Eliminates the detailed QR data preview and its expand/collapse toggle. The `qrDataPreview` element is now used *only* to display errors if QR generation fails.
2.  **Simplifies Payment Options:** Removes the toggle button for showing/hiding QR payment options (Asset, Amount, Memo); these are now always visible.
3.  **Optimizes QR Data:** Removes timestamp and version fields from the generated QR data to reduce its size.
4.  **Adjusts Styles:** Updates related CSS for the Receive modal, QR display, and removed elements.
> Optimize QR Codes for Max Memo Length and Improve Receive Modal Layout

- app.js
* Change version from 'k' to 'r' for application updates.
* Clear input fields in the send modal when opened to ensure a fresh state for user input.
* Clear existing fields in the `fillPaymentFromQR` function before populating with new data for better user experience.
> clear input fields in send modal and QR payment functions

- index.html
* Set maxlength of message input and memo textarea to 2000 characters to enhance user input control and prevent excessive text entry.
> Add maxlength=2000 attribute to textareas for message-input and memo textarea

- index.html
- styles.css
**Summary:**
This PR updates the styling for several text input areas (`.message-input`, `#sendMemo`, `#receiveMemo`) to visually hide their scrollbars across different browsers while ensuring they remain scrollable when the content overflows. It also adjusts the viewport meta tag for better behavior with interactive widgets on mobile android devices.
**Changes:**
*   **index.html:**
*   Added `interactive-widget=resizes-content` to the `viewport` meta tag to ensure the layout resizes correctly when virtual keyboards or other interactive widgets appear for android devices
*   **styles.css:**
*   Updated `.message-input`:
*   Changed `overflow-y` from `hidden` to `auto`.
*   Added `-webkit-overflow-scrolling: touch` for mobile scrolling behavior.
*   Added `scrollbar-width: none` to hide …
> message input overflow=auto & visually remove scroll bar & update viewport meta

- app.js
**Summary:**
*   Updates the message search functionality to highlight the entire message preview in the results list, rather than just the specific search term occurrences.
*   Removes the step that added `<mark>` tags around specific matches within the `searchMessages` function.
*   Modifies `displaySearchResults` to wrap the complete, HTML-escaped message preview string in `<mark>` tags before rendering.
*   Removes the `linkifyUrls` call from the search result message preview display.
BEFORE:
> Modify Search Result Highlighting Logic

- app.js
**Refactor: Improve Receive Modal Event Handling**
*   **Prevent Multiple Listeners:** Refactored the event listeners for the Receive Modal inputs (`#receiveAsset`, `#receiveAmount`, `#receiveMemo`). Listener attachment was moved from `openReceiveModal` to the `DOMContentLoaded` handler, ensuring they are attached only once and preventing the creation of duplicate listeners when the modal is reopened.
*   **Simplify Cleanup:** Removed the corresponding event listener cleanup logic from `closeReceiveModal`, as it's no longer necessary.
*   **Debounce Input Updates:** Applied `debounce` to the `input` event listeners for the amount and memo fields. This optimizes performance by preventing the `updateQRCode` function from executing excessively while the user is typing.
> Improve Receive Modal Event Handling*

- app.js
Task: The `requestNotificationPermission` view doesn’t exist in the .html page, but it’s getting called. Looks like we can remove it. - Jai  Raj
- Remove unused getElement. 
- Removed unused commented out code.
> Remove unused getElement. Removed unused commented out code.

- app.js
`if (added > 0) ` condition can be removed, as it’s already under the same condition check
> remove redundant check in processChats

- app.js
- data_structures_flow/timestamp/appendChatModal_option2.md
- data_structures_flow/timestamp/list_rendering.md
- data_structures_flow/timestamp/timestamp.md
**PR Summary: Update Chronological Ordering and Rendering Logic to use `sent_timestamp`**
**Goal:** This PR addresses bugs related to the chronological display of items in several parts of the application, primarily the main chat list (`#chatList`) and the chat modal (`#chatModal .messages-list`). It ensures that both outgoing and incoming messages/transactions result in correctly sorted data arrays and that the UI accurately reflects this sorted order in real-time.
---
**I. Data Storage & Manipulation Changes (`app.js`)**
The core principle applied here is to consistently use the `insertSorted()` helper function (introduced previously) to maintain descending chronological order (newest first) based on timestamps within our core data arrays.
1.  **`handleSendAsset()`:**
*   **Data:** When …
> Update Chronological Ordering and Rendering Logic to use `sent_timestamp`

- app.js
**Title:** Fix: Prevent missed messages by delaying timestamp update
**Summary:**
*   **Problem:** Messages could be missed if multiple updates arrived close together because the "last seen" timestamp (`myAccount.chatTimestamp`) was being updated *inside* the loop processing senders, leading to inconsistent fetch times for subsequent senders in the same batch.
*   **Fix:**
*   The initial `timestamp` used for fetching messages is now read *once*, *before* the loop iterating through senders begins.
*   This ensures the same starting point is used for fetching messages for all senders in the current batch.
*   The calculation of the latest timestamp received (`newTimestamp`) remains, tracking the maximum timestamp across all messages in the batch.
*   The update to the global …
> Fix: Prevent missed messages due to timestamp updating too early in processChats

- app.js
- styles.css
**Summary:**
*   **Wallet History Notification:**
*   Added a visual notification dot (using CSS `::after` pseudo-element) to the "History" button on the Wallet screen (`#openHistoryModal`).
*   The dot appears when a new transaction notification is received via WebSocket while the user is not on the Wallet tab.
*   The notification dot is automatically removed when the user clicks the "History" button to open the transaction history modal.
*   **CSS:**
*   Added `position: relative` to `.wallet-action-button` to allow absolute positioning of the notification dot.
*   Added new CSS rules for `.wallet-action-button::after` to define the dot's appearance (hidden by default).
*   Added `.wallet-action-button.has-notification::after` rule to make the dot visible when the class is present.
> Feat: Add notification dot to Wallet History button for new transactions

- app.js
- network.js_web
**Summary:**
*   **Fixes Message Highlighting:** Resolves an issue where incoming messages weren't reliably highlighted when the user sent a message immediately after receiving one.
*   **Conditional Highlight:** Introduces a `triggeredByWebSocket` flag passed from `WSManager` -> `updateChatList` -> `appendChatModal`.
*   **Targeted Scroll/Highlight:** `appendChatModal` now scrolls to and highlights the *last received message* only if the update was triggered by a WebSocket notification (`triggeredByWebSocket` is true). This prevents unwanted scrolling/highlighting when sending messages or on initial modal load.
*   **Reliability:** Removes dependency on the previous `newMessageTimestamps` mechanism for highlighting.
*   **Configuration:** Updates gateway and WebSocket URLs in …
> Conditionally Highlight Chat Messages on WebSocket Update

- app.js
Problem if navigating through historyModal, contactInfoModal stayed open and if going into another chatModal from historyModal would direct to previously opened contactInfoModal instead of correct chatModal.
> fix: Close contact info modal when clicking on history item

- app.js
Feature: Always Play Transfer Sound
Changes:
- Modified the transfer sound behavior to play for all incoming transfers
- Removed conditional check that prevented sound from playing when wallet screen or history modal was active
- Ensures users are notified of incoming transfers regardless of which screen they're viewing
> Refactor sound playback logic in processChats function

- app.js
- index.html
- Removed the "Check Update" button from the welcome screen in `index.html`
- Removed the `clearCacheButton` event listener and related code from `app.js`
- Removed references to the button in the welcome buttons setup code
- Streamlines the user interface by removing an unnecessary button
- Reduces code complexity by removing unused functionality
- Maintains core application functionality while improving UI clarity
- Verified that the welcome screen displays correctly without the Check Update button
- Confirmed that all other welcome screen buttons (Sign In, Create Account, Restore Account, Install) function as expected
- Ensured that the application's update checking functionality remains intact through other mechanisms
> feat(welcome): Remove check update (clear cache) button and its associated functionality from app.js and index.html.

- app.js
- network.js
- network.js_web
- styles.css
*   **Problem:** Chat list previews only displayed text messages, and payment transactions were not explicitly styled or handled differently from regular messages in the chat view. The mechanism for highlighting the newest received message in the chat modal was potentially fragile. Network configurations were set to localhost.
*   **Changes:**
*   Updated `updateChatList` to display a specific format for payment previews in the main chat list, including direction, amount, symbol, and an optional truncated memo.
*   Refactored `appendChatModal` to explicitly render and style payment transactions differently from chat messages within the chat modal, using dedicated CSS classes for payment details (direction, amount, memo).
*   Improved the newest received message highlighting logic in …
> Feature: Integrate Payments into chatModal

- app.js
*   **Immediate Chat List Update for Sent Transfers:** Update `myData.chats` immediately after sending a transfer to ensure the chat appears at the top of the list.
*   **Correctly Count Incoming Transfers:** Increment the `added` counter when processing incoming transfer messages in `processChats`.
*   **Suppress Transfer Notifications:** Prevent toast notifications for incoming transfers if the user is not actively viewing that specific chat.
> Ensure initial transfers appear in chatList if sender/receiver has never sent payment to user

- app.js
**Problem:**
- Client-side timestamps based on `Date.now()` can be inaccurate if the user's local clock is off.
- Fetching accurate time from external APIs was unreliable in Firefox due to Enhanced Tracking Protection (ETP) and CORS-like errors.
- Previous attempts with other APIs (e.g., worldtimeapi.org, worldclockapi.com) had issues with browser compatibility or time parsing.
**Solution:**
- Switched the time source to [TimeAPI.io](https://timeapi.io/api/time/current/zone?timeZone=UTC), which provides a reliable UTC time in JSON.
- Updated the `timeDifference` function to:
- Fetch UTC time from TimeAPI.io.
- Correctly parse the `dateTime` field as UTC by appending a `Z` if missing, ensuring accurate skew calculation regardless of local timezone.
- Store the calculated skew in the global …
> fix: Implement timeapi.io with Retry for Firefox ETP Issue

- app.js
- Added automatic clearing of notification bubbles in `closeHistoryModal` function
- Clears notifications from both the History button and Wallet tab button when modal is closed
- Improves user experience by automatically clearing notifications after viewing transactions
- Eliminates the need for users to manually click buttons to clear notifications they've already seen
- Makes the notification system more intuitive - if a user has viewed the transaction in the modal, they shouldn't need to take additional action to clear the notifications
- Verified that notification bubbles are cleared when:
- Closing the modal after viewing a new transaction
- Closing the modal normally
- Opening and closing the modal multiple times
- Confirmed that notifications still appear correctly for new …
> Fix closeHistoryModal function to remove notification classes from history modal triggers, enhancing UI feedback on modal closure.

- app.js
- index.html
- styles.css
Summary:
*   Adds 'Validator' option to the main menu (`#menuModal` in `index.html`).
*   Creates 'Validator Options' modal (`#validatorModal`) accessible from the menu:
*   Includes styled 'Stake' (primary) and 'Unstake' (danger) buttons.
*   Adds concise descriptions below each button.
*   Creates 'Stake Validator' modal (`#stakeModal`) opened from `#validatorModal`:
*   Contains a form (`#stakeForm`) with 'Validator Node Address' (`#stakeNodeAddress`) and 'Stake Amount' (`#stakeAmount`) inputs.
*   Includes a primary-styled 'Submit Stake' button (`#submitStake`).
*   Creates 'Unstake Validator' modal (`#unstakeModal`) opened from `#validatorModal`:
*   Contains a form (`#unstakeForm`) with 'Validator Node Address' (`#unstakeNodeAddress`) input.
*   Includes a danger-styled 'Submit …
> validator staking menu item and modals

- app.js
- Updated stake transaction:
- Changed type from "stake" to "deposit_stake".
- Now includes nominator (from myAccount.keys.address), nominee, stake amount, and timestamp.
- Updated unstake transaction:
- Changed type from "unstake" to "withdraw_stake".
- Now includes nominator, nominee, force (set to false), and timestamp.
- Removed legacy and commented-out transaction formats for clarity.
> Refactor Stake/Unstake Transaction Payloads for Correct/New Backend API

- app.js
• Removes `longAddress()` wrapper from `nodeAddress` in stake/unstake transactions
• Affects two locations in `app.js`:
- Deposit stake transaction
- Withdraw stake transaction
• Rationale: Node addresses should be used in their original format without padding
Note: This change appears to fix an issue where node addresses were being incorrectly padded with zeros, which would cause validation errors for 64-character addresses that don't follow the expected 40+24 zeros pattern.
> Fix: Standardize Node Address Handling in Staking Operations

- app.js
- index.html
- styles.css
**`app.js`**
*   Replaced `openUnstakeModal` with `confirmAndUnstakeCurrentUserNominee` function.
*   Added browser `window.confirm()` dialog before initiating unstake transaction via `submitUnstakeTransaction`.
*   Implemented `submitUnstakeTransaction` to handle the unstake API call and feedback toasts.
*   Modified `openValidatorModal` to:
*   Fetch the unstake button (`#submitUnstake`).
*   Dynamically disable/enable the unstake button based on the presence of a `nominee`.
*   Updated `submitUnstakeTransaction` success handler to manually refresh relevant UI elements in the Validator modal instead of re-calling `openValidatorModal`.
*   Removed unused functions: `openUnstakeModal`, `closeUnstakeModal`, `handleUnstakeSubmit`.
*   Removed event listeners associated with the old unstake …
> Refactor: Unstake Process and Validator Modal UI Enhancements

- app.js
- index.html
- lib.js
- styles.css
This PR enhances the "Stake Validator" modal by adding available balance display and comprehensive input validation.
**`app.js`**
*   Applied debounce (300ms) to `input` listeners for `stakeNodeAddress` and `stakeAmount` fields in the stake modal, calling `validateStakeInputs`.
*   Refactored `openValidatorModal` to store the calculated minimum stake amount (formatted string) in `stakeForm.dataset.minStake`.
*   Updated `openStakeModal`:
*   Displays the user's available LIB balance in the new `#stakeAvailableBalanceDisplay` element.
*   Reads the minimum stake amount from `stakeForm.dataset.minStake` (set by `openValidatorModal`) to pre-fill the amount input.
*   Calls `validateStakeInputs` on open for initial state.
*   Created `validateStakeInputs` function:
*   Gets necessary …
>  Feat: Add Balance Display and Validation to Stake Modal

- app.js
- index.html
**`app.js`**
*   Added new handler function `fillStakeAddressFromQR` to populate the stake address field with scanned QR data (expects plain text address).
*   Refactored `handleSuccessfulScan` to remove generic prefix check and delegate format validation to context-specific `fill...` functions.
*   Enhanced `fillPaymentFromQR` to include explicit `liberdus://` prefix validation and improved error handling.
*   Updated `openStakeModal` to set `openQRScanModal.fill = fillStakeAddressFromQR` when the modal opens.
*   Simplified the event listener for `#scanStakeQRButton` in `DOMContentLoaded` to directly call `openQRScanModal`.
**`index.html`**
*   Added a scan button (`#scanStakeQRButton`) next to the "Validator Node Address" input field within the `#stakeModal`.
*   Wrapped the address …
> Feat: Add QR Code Scanning for Stake Validator Address

- app.js
- index.html
**Summary:**
*   Updated the custom validity message for the send amount input field.
*   Replaced the long decimal representation (0.000000000000000001 LIB) with Unicode-based scientific notation (1×10⁻¹⁸ LIB) for better readability when the entered value is less than 1 wei.
> Improve Wei Validation and Validation message (stakeModal & sendModal)

- app.js
- index.html
- styles.css
* Remove the message element from the DOM and replace it with toast notifications for success and error messages during account restoration.
* Update the success and error handling logic to utilize the showToast function for improved user feedback.
* Clean up related CSS styles by removing the now-unnecessary success message styles.
> Refactor Restore Account Modal to Use Toast Notifications

- app.js
- index.html
Update username availability check and prevent self-sending of assets
* Adjust the order of username availability checks to improve logic flow.
* Disable the send button and show a toast notification if the user attempts to send assets to their own account.
* Reposition balance warning display in the send asset form to show up underneath the input for consistent UI
> Prevent Self-Interaction (sendAsset)

- app.js
Uncomments the amount conversion logic (`bigxnum2big`) within the
`handleStakeSubmit` function. This resolves a "Cannot mix BigInt and
other types" error that occurred because the stake amount string was not
being converted to a BigInt before being used.
The explicit check `if (amount_in_wei <= 0n)` was removed as minimum
stake and balance validation are handled separately. The surrounding
try-catch block remains to handle potential conversion errors from
invalid user input in the amount field.
> fix(stake): Fix BigInt type error in stake submission

- app.js
- index.html
- styles.css
**Overview:**
This pull request refactors the handling of failed messages by introducing a new pop-up dialog modal. This provides users with clear options to retry or delete a failed message, improving user experience and error recovery. The changes also include a bug fix for message removal and cleaner event listener management for the new modal.
**Key Changes:**
*   **New Failed Message Modal (`failedMessageModal`):**
*   **HTML (`index.html`):** A new modal structure (`failedMessageModal` with class `modal-dialog`) has been added to display options for failed messages.
*   **CSS (`styles.css`):**
*   The `failedMessageModal` is styled as a compact, centered pop-up dialog box with a backdrop, distinct from the existing full-screen modals.
*   The "Retry" and "Delete" buttons within this …
> Failed Message Handling with Pop-up Dialog

- app.js
- index.html
**PR Summary:**
This pull request significantly improves the user experience for handling failed messages and ensures proper cleanup of data when resending.
*   **Updated "Retry" Functionality and Wording:**
*   **`index.html`:** The button in the `failedMessageModal` previously labeled "Retry" has been renamed to **"Edit & Resend"** to more accurately reflect its behavior (populating the main chat input for user review/editing before resending).
*   **Resending Failed Messages - Data Cleanup:**
*   **`app.js` (`handleSendMessage`)**:
*   When a message is sent, the function now checks the hidden input `retryOfTxId` (populated when "Edit & Resend" is used).
*   If `retryOfTxId` contains a transaction ID, `removeFailedTx()` is called with this ID. This ensures that the original failed …
> Enhance Failed Message Handling: "Edit & Resend" and Cleanup

- app.js
**PR Summary:**
This pull request focuses on `app.js` to improve the logic for resending failed messages, handling immediate send failures more gracefully, and refining the cleanup of failed transaction data.
*   **Corrected `txid` Handling for Resending Messages:**
*   **`app.js` (`handleSendMessage`):**
*   When a message is being resent (identified by a `txid` in the `retryOfTxId` hidden input), the `removeFailedTx()` function is now correctly called with both the `retryTxId` and the `currentAddress` of the chat. This ensures the original failed message is properly removed from the specific contact's message list and the shared wallet history before the new send attempt.
*   **`app.js` (`handleFailedMessageDelete`):**
*   When a user chooses to delete a failed message via the …
> Improve Failed Message Resend Logic & injecttx error handling

- app.js
- index.html
**`app.js`**
*   **New Modal for Failed Payment Items:**
*   Added event listeners for a new modal `failedPaymentModal`. This includes listeners for retry, delete, and close buttons, as well as a backdrop click. (Previously `failedHistoryModal`)
*   `handleFailedPaymentClick(txid, element)`: This new function is triggered when a failed transaction item is clicked. It retrieves transaction details (address, memo, assetID) from the clicked element or existing modal data and stores them. It then displays the `failedPaymentModal`. (Previously `handleFailedHistoryClick`)
*   `handleFailedPaymentRetry()`: A new placeholder function for handling the retry logic for a failed transaction. (Previously `handleFailedHistoryRetry`)
*   `handleFailedPaymentDelete()`: This new function handles the …
> Feature: Failed Transaction Handling Modal

- app.js
- index.html
**Summary:**
*   **Introduced Retry Mechanism for Failed Payments:**
*   Added a new hidden input field `retryOfTxId` to the send modal (`index.html`) to store the transaction ID of a payment being retried.
*   Implemented a new function `handleFailedPaymentRetry()` in `app.js`:
*   This function is invoked when a user opts to retry a failed payment.
*   It closes the "failed payment" modal.
*   It opens the "send" modal and pre-fills the recipient address, amount, and memo from the original failed transaction.
*   The `txid` of the failed payment is stored in the `retryOfTxId` hidden field.
*   **Updated Send Modal and Transaction Handling:**
*   `openSendModal()` in `app.js` now clears the `retryOfTxId` field.
*   `handleSendAsset()` in `app.js` now checks if `retryOfTxId` is populated: …
> Feat: Implement Retry Failed Payment Functionality

- app.js
Enhance transaction history management by adding unstake transaction details and updating the amount field for withdraw_stake transactions. This improves tracking and accuracy of wallet history. Additionally, refactor the handling of transaction amounts to ensure consistency across stake and unstake operations.
> Enhance transaction history management by adding unstake transaction

- app.js
Enhance error handling and user feedback for pending transactions in validator modal
* Update toast notifications to provide specific failure messages for stake and unstake transactions, improving clarity for users.
* Implement logic to refresh the validator modal when a stake or unstake stake transaction fails, ensuring accurate wallet history display.
* Clean up code for better readability and maintainability.
> Enhance error handling and user feedback for pending stake/unstake transactions in validator modal

- app.js
- update toast notification duration to 3 seconds
- close and open validatorModal to refresh and show pending skeleton
> Update toast notification duration and streamline transaction submission logic in validator modal

- app.js
Update checkPendingTransaction to check for stake and unstake tx. 
- While differentiating between stake and unstake transaction success messages, enhancing user feedback during transaction processing.
> Update checkPendingTransaction to handle succesful unstake receipt

- app.js
- styles.css
Adds a close button to error toasts that must be pressed to dismiss the toast.
> feat(app): keep error toasts until dismissed by user

- app.js
This PR updates the `validateStakeInputs` function in `app.js` to more accurately determine the minimum stake required by considering the user's existing stake on a node.
**Changes in `app.js`:**
*   **Asynchronous Operation:**
*   The `validateStakeInputs` function is now `async` to support `await` for network calls.
*   **Fetch User's Current Stake Information:**
*   The function now queries the network for the user's account details using `queryNetwork(\`/account/\${address}\`)`, where `address` is the user's long address.
*   It retrieves `staked = res?.account?.operatorAccountInfo?.nominee` to check if the user is staked to any node.
*   **Calculate Effective Minimum Stake:**
*   If the user is found to be staked:
*   It retrieves the `stakedAmount` in hexadecimal from …
> Refactor Stake Input Validation to Account for Existing Stake

- app.js
**Summary:**
*   Introduced a `thirtySecondsAgo` constant to define a new timeout threshold.
*   **Modified API endpoint selection:**
*   The endpoint path is initialized to `/transaction/<txid>`.
*   It's updated to `/old_receipt/<txid>` if `submittedts < twentySecondsAgo || submittedts < thirtySecondsAgo`.
*   *Note: The condition `submittedts < twentySecondsAgo || submittedts < thirtySecondsAgo` simplifies to `submittedts < twentySecondsAgo` because if a timestamp is less than `thirtySecondsAgo`, it will inherently be less than `twentySecondsAgo`.*
*   **Implemented transaction timeout and removal:**
*   If a transaction is older than 30 seconds (`submittedts < thirtySecondsAgo`) AND the network query result (`res.transaction`) is `null`, the transaction is considered timed out.
* …
> checkPendingTransactions query for old receipts after tx is 20 seconds old

- app.js
Note that regular transactions may also have 'stake/unstake' as memo and these will open validator modal as well.
> feat(history-click): Add memo check for stake/unstake transactions in handleHistoryItemClick function

- app.js
Remove toast notification for unstake failure in submitUnstakeTransaction function, since handled in injectTx. Improve error logging for API response failures.
> Remove redundant toast notification for unstake failure in submitUnstakeTransaction

- app.js
- index.html
**PR Summary: Hide Private Key Input Behind Checkbox in Create Account Modal**
- **UI/UX Improvement:**  
- The "Private Key" input on the Create Account modal is now hidden by default.
- Added a checkbox labeled **"Use my own private key (Advanced)"**.  
- When checked, the private key input field and its description are revealed.
- **JavaScript Logic:**  
- Added a `handleTogglePrivateKeyInput` function in `app.js` to toggle the visibility of the private key section and clear its value when hidden.
- Registered the checkbox change event in the DOMContentLoaded block for proper initialization.
- **User Guidance:**  
- Reduces confusion for new users by hiding advanced options unless explicitly requested.
---
This change makes the account creation process simpler and less error-prone for …
> Hide Private Key Input Behind Checkbox in Create Account Modal

- app.js
- index.html
- styles.css
* Introduced a button to toggle between LIB and USD for the send amount, enhancing user experience by allowing users to view and send amounts in their preferred currency.
* Implemented the `handleToggleBalance` function to update the balance symbol and convert amounts based on the selected currency.
* Updated the send form submission logic to account for the selected currency, ensuring accurate transaction amounts are processed.
* Enhanced the UI with new styles for the toggle button and input field layout for better usability.
> Add toggle functionality for LIB/USD balance in send modal

- app.js
* Added event listeners to handle tab key navigation for the send message button and back buttons, improving accessibility and user experience.
* Implemented functions to prevent default tabbing behavior, ensuring buttons are not focused when navigating through the page with the tab key.
* Updated the app.js file to include these new functionalities, enhancing overall usability in the chat interface.
> Fix tab and shift+tab from getting into scanQRModal in chatModal

- app.js
- index.html
* Added event listeners for the newly introduced 'last-item' anchor tags to handle tab key navigation, improving accessibility.
* Updated the app.js file to focus on the last-item in the footer when switching view to chatsScreen, enhancing user experience.
* Refactored the `ignoreTabKey` and `ignoreShiftTabKey` functions to include detailed comments for clarity on their purpose.
* Modified index.html to include multiple 'last-item' anchor tags for better navigation control in various modals.
> Do not allow tab while on last item to prevent switching pages

- app.js
- index.html
* Changed event listener from '.first-item' to '.logo-link' to consolidate to already implemented unique class.
* Removed redundant ID from the logo link in index.html to streamline the code.
> Consolidate to use just logo-link class for shift-tab preventation 

- app.js
Remove vibration feedback from playChatSound and playTransferSound functions to prevent silent errors causing problems with updateChatList
> Remove vibration feedback that was causing silent error for unsupported browsers

- app.js
- Modified the display of the current toll value to include the currency symbol (LIB) when the toll is set.
- Refactored the conversion logic for the toll value based on the selected currency, ensuring accurate representation in both LIB and USD formats.
- Enhanced user feedback by updating the toll display dynamically based on currency selection.
> Update TollModal to display `currentTollValue` based on toggled USD or LIB

- app.js
- Changed the endpoint path for old receipts from `/old_receipt/${txid}` to `collector/api/transaction?appReceiptId=${txid}` to align with new API structure.
> fix: Update endpoint path for old receipts in checkPendingTransactions function

- app.js
- Changed the handleSendAsset function to await validateBalance for accurate balance validation.
- Simplified amount handling by using the already converted 'amount' in wei, removing unnecessary conversions for clarity and efficiency.
> fix: Update handleSendAsset to use validated amount directly in wei

- app.js
- Added a check in the handleVisibilityChange function to return early if myAccount is not defined, preventing unnecessary state saving when the user is not logged in.
> fix: Prevent state saving on visibility change if no account is present

- app.js
Was causing silent error and preventing pending transaction from getting removed when knowing there was an error.
- Replaced the standalone `refreshCurrentView` function with a method in the `ChatModal` class to improve encapsulation and maintainability.
- Enhanced the `refreshCurrentView` method to conditionally refresh the chat modal and chat list based on the active view and the failed transaction ID.
- Updated calls to refresh the UI components upon transaction failures, ensuring a more cohesive user experience.
> Refactor refreshCurrentView and put into chatModal class

- app.js
Disable buttons and inputs during submission and re-enabling them on validation failures or errors. 
This improves user experience by preventing multiple submissions and providing clearer feedback on account creation status.
> Have createAccountModal disable all elements while pending create account

- styles.css
- improve layout on FireFox with safe area insets while also improving Iphone display as well. Firefox and Iphone screenshots below
Firefox
Iphone
> Adjust padding in message input container 

- app.js
Update read transaction logic in ChatModal class to check for amount property before sending
- Modified the close method to ensure a read transaction is only sent if the newest received message does not have an amount property, improving transaction handling and preventing unnecessary calls.
> Fix: Only send read messages for message types and not transfers in the chatModal

- app.js
- Added user response tracking to prevent unnecessary read transactions
- Improved read transaction logic to only trigger when:
- There is a newest received message
- The message doesn't have an amount property
- The user hasn't responded to the message
- Added `hasUserResponded()` method to check if the last message is from the user and not a payment message
- Added `userResponded` flag to track user interaction state
- Reset `userResponded` flag when opening chat modal
- Enhanced `close()` method to check user response before sending read transaction
- Added message list validation to determine if user has responded
- Reduces unnecessary read transactions
- Improves user experience by better handling message read states
- More accurate tracking of user interactions with messages
> Add user response tracking and update read transaction logic in ChatModal class

- app.js
1. **Method Renaming and Logic Refinement**
- Renamed `hasUserResponded()` to `needsToSend()` to better reflect its purpose
- The method now has a more comprehensive check for when read transactions should be sent
2. **Read Transaction Logic Improvements**
- Added new conditions for sending read transactions:
- Checks if the contact has messages
- Verifies if the other party needs to pay toll
- Considers friend status (friend === 2 or 3)
- Looks for the last relevant non-payment message
- Compares message timestamps with contact timestamp
3. **Code Structure Changes**
- Removed redundant timestamp comparison in `sendReadTransaction()`
- Simplified the read transaction sending logic
- Removed nested conditional blocks for better readability
4. **Key Logic Changes**
- Previously: Only …
> Update `needsToSend` have all checks and isolate `sendReadTransaction` to just tx posting

- app.js
- data_structures_flow/offline-fliw.md
- data_structures_flow/qr-code-flow.md
- index.html
- styles.css
- **Class and Variable Renaming**
- Renamed `SendModal` class to `SendAssetFormModal`
- Renamed `sendModal` instance to `sendAssetFormModal`
- Updated all related variable names and comments for consistency
- **HTML Element Updates**
- Renamed modal IDs:
- `sendModal` → `sendAssetFormModal`
- `sendConfirmationModal` → `sendAssetConfirmModal`
- Updated button IDs:
- `openSendModal` → `openSendAssetFormModal`
- `closeSendModal` → `closeSendAssetFormModal`
- `closeSendConfirmationModal` → `closeSendAssetConfirmModal`
- **CSS Updates**
- Updated all CSS selectors to match new modal IDs
- Maintained all existing styles and functionality
- **Documentation Updates**
- Updated comments in code to reflect new naming
- Updated flow documentation in `qr-code-flow.md`
---
**Technical Notes:**
- This …
> Rename Send Modal to Send Asset Form Modal for Clarity

- app.js
- Implemented a check to update `tollAmountLIB` and `tollAmountUSD` to the old value if the toll modal is currently active, ensuring accurate display of toll values after reverting changes.
- Enhanced user experience by maintaining consistency in toll value representation during transaction checks.
> Fix: Refresh tollModal value display when pending failed and when toll modal is active

- app.js
Defaulting to 1 (toll required) when chatId has not been estalished and setting up `tollInfo` object
> Update tollInfo assignment to handle undefined values gracefully in SendAssetFormModal

- app.js
- Changed the display format for toll information to use '=' instead of parentheses for clarity.
- Updated the toll display in SendAssetFormModal to use HTML for styling, ensuring the "Toll:" label is black.
- Enhanced user feedback by improving the visual representation of toll information in both components.
> Update toll display formatting in app.js and SendAssetFormModal for consistency

- app.js
- Updated the function to use the current network toll timeout for validating the timestamp of the newest sent message, enhancing accuracy in determining whether to skip the reclaim toll transaction.
- Removed outdated console logs and replaced them with more relevant logging for better clarity on the validation process.
> Refactor sendReclaimTollTransaction in ChatModal to improve timestamp validation logic

- app.js
- Implemented a HEAD request to verify if the notice.html file exists and retrieve its Last-Modified timestamp.
- Added logic to determine if the notice should be displayed based on the file's modification time compared to the current settings.
- Enhanced user experience by preventing unnecessary downloads of unchanged content.
> Add system notice fetching logic to check file existence and modification timestamp

- app.js
Recalculate time skew and prompting user to try again.
> Handle timestamp out of range error in tx injection 

- app.js
- index.html
* Introduce constants for maximum memo and chat message byte sizes.
* Implement memo size validation logic and update UI to display remaining bytes.
* Modify the SendAssetFormModal to include memo byte counter and validation checks before submission.
> Add memo byte size validation in SendAssetFormModal

- app.js
- index.html
- styles.css
- **Reason**: Enhance user experience by making contact information fields clickable and actionable
- **Changes Made**:
- **HTML**: Converted Email, LinkedIn, and X-Twitter fields from static `<div>` elements to clickable `<a>` elements with proper security attributes (`target="_blank"`, `rel="noopener noreferrer"`)
- **CSS**: Added `.contact-info-link` styling class that matches the existing `.about-link` design pattern for consistent visual appearance
- **JavaScript**: Updated `updateContactInfo()` method to set appropriate URLs:
- Email: `mailto:` protocol to open default email client
- LinkedIn: `https://linkedin.com/in/{username}` to open profile in new tab
- X-Twitter: `https://x.com/{username}` to open profile in new tab
- **UX Improvement**: Users can now directly interact with …
> Add clickable links for Email, LinkedIn, and X-Twitter in contact info modal

- app.js
Now will render `showEmptyState()` when no tx history present
> Fix HistoryModal asset check to validate wallet history instead of assets

- styles.css
- Chat modal titles with long names/usernames were overflowing and overlapping with header action buttons
- Contact names in the contact info section needed better text wrapping for long names
- **Added text truncation to modal titles** with ellipsis for long names
- **Made chat user info container responsive** with proper spacing for header actions
- **Added responsive breakpoints** for mobile devices (min-width adjustments)
- **Improved contact name text wrapping** with word-break properties
- **Removed duplicate CSS rules** for `.chat-user-info` hover states
The changes ensure that long contact names are properly handled in both the chat modal header and contact info sections, preventing layout overflow while maintaining readability across different screen sizes.
> Fix Chat Modal Title Overflow and Improve Text Wrapping

- styles.css
**Reason for PR:** Fixed modal transition issues where the save button wasn't being disabled after first press, causing transition problems.
**Changes made:**
- **Fixed modal visibility system**: Replaced `display: none/block` with `opacity: 0/1` and `pointer-events: none/auto` to enable smooth CSS transitions
- **Improved modal positioning**: Added proper opacity and pointer-events states to allow the `transform: translateX(-100%)` transition to work smoothly
- **Enhanced user interaction**: Ensured modals are fully interactive when visible while preventing interaction when hidden
- **Maintained existing functionality**: Preserved all existing modal behavior while fixing the transition animation
The key fix was changing from `display` properties (which don't animate) to `opacity` and …
> Modal Transition Fix

- app.js
• Standardizes modal initialization pattern across all modal classes
• Improves code maintainability by centralizing DOM element references in load() methods
• Ensures consistent event listener setup timing
• **SignInModal**: Moved DOM element references from constructor to `load()` method and added `preselectedUsername` property
• **FriendModal**: Refactored to store DOM elements in `load()` method and renamed `openFriendModal()` to `open()`
• **TollModal**: Moved all DOM element references and event listeners to `load()` method
• **InviteModal**: Restructured to initialize DOM elements in `load()` method
• **AboutModal**: Moved DOM element references from constructor to `load()` method
• **ContactModal**: Refactored to store DOM elements in `load()` …
> Refactor Modal Initialization: Move DOM Element References to load() Methods

- app.js
deletes the pqEncSharedKey friend in both message and transfer transactions right after it is used be the decription so that the field is not stored in local storage.
> Don't store pqEncSharedKey with each message

- app.js
Ensure that the QR fill functions in both StakeValidatorModal and SendAssetFormModal are bound to the correct context for proper functionality.
> Bind QR fill functions to the correct context in modals

- crypto.js
In ios Safari encrypting backup with a password will fail due to max call stack.
Improve performance in Safari by yielding every 1000 iterations during key derivation in the encryptData function.
> Optimize key derivation in encryptData function for Safari performance

- app.js
- index.html
- network.js
- network.js_loc
- network.js_web
This PR introduces a new backup account functionality and addresses network parameter naming inconsistencies across the application.
**New Features:**
- Implemented backup button in welcome screen and menu modal
**Bug Fixes:**
- Fixed inconsistent parameter naming: changed `netid` to `networkId` across all transaction objects for better consistency
- Updated parameter names in friend requests, asset transfers, alias registration, toll payments, validator staking, and chat operations
**UI/UX Improvements:**
- Added backup button to welcome screen for existing users
- Integrated backup functionality into main menu modal
**Code Quality:**
- Improved object property checking using `Object.prototype.hasOwnProperty.call()` instead of direct property access
- Fixed method scope issues in …
> Add Backup Account Feature and Fix Network ID Parameter

- app.js
- **Reason for PR:**  
Previously, when the app was locked and the user clicked "Import Account," user did not sign in causing problem when importing. This was due to missing logic in the unlock flow to handle the import account button.
- **Changes Made:**  
- Updated the event handler for `importAccountButton` to check for lock status and open the unlock modal if needed, mirroring the logic for other account actions.
- Enhanced the `UnlockModal` logic to track which button triggered the unlock modal. After a successful unlock, it now correctly opens the Restore Account modal if the import account button was used.
- No changes to network.js are included in this summary.
> Fix: Password unlock now needed for restore modal when app is locked

- app.js
This PR updates the backup export logic to support React Native WebView environments. When the app is running inside a WebView, the backup file (JSON blob) is converted to a base64 data: URL and sent via window.ReactNativeWebView.postMessage.
This ensures the file can be received and handled natively on the mobile side, where direct downloads via blob: URLs or <a download> don't work reliably.
> Handle backup export via postMessage for React Native WebView

- app.js
- index.html
- styles.css
- Changed balance warning display style from 'block' to 'inline' for better integration with the UI.
- Updated HTML structure to include balance warning directly within the label for the amount input.
- Adjusted CSS for balance warning to ensure consistent styling and visibility.
> Update balance warning display style and improve user feedback in asset transfer forms

- app.js
Fixes this error `app.js:4502 Encryption failed: TypeError: Cannot read properties of null (reading 'username')`
> Fix filename generation in BackupAccountModal to use default method without username since myData not present

- app.js
- crypto.js
- encryption.worker.js
- index.html
- when a file is selected it is encrypted via a web worker
- change to crypto.js use globalThis instead of window since window is [not available to workers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description) 
- nothing happens with the encrypted file yet, next step will be to upload and get a url to download
> Encrypt attachment with webworker

- app.js
- To enable users to send file attachments in chat messages, with attachment metadata (URL, name, size) encrypted for privacy, similar to how memos are handled.
- **Attachment Extraction & Encryption:**
- Extracts `url`, `name`, and `size` from each file in `this.fileAttachments`.
- Encrypts this array using the same method as the memo field (`encryptChacha` with the derived DH key).
- **Payload Update:**
- Adds a new `xattach` field to the message payload, containing the encrypted attachment metadata.
- The `xattach` field is only included if there are attachments.
- **Optimistic UI Update:**
- Adds the unencrypted attachment metadata to the local message object for immediate UI feedback.
- **Cleanup:**
- Clears `fileAttachments` and updates the …
> Add Encrypted File Attachment Support to Chat Messages (`xattach` field)

- app.js
Enable users to download and decrypt attachments directly by clicking on them in the chat interface. This enhances user experience by streamlining the process of accessing shared files.
> Implement click-to-download and decrypt for attachments

- app.js
- styles.css
- To provide a user-friendly, privacy-respecting way to display deleted payment transactions in the transaction history, matching the app’s flat design system.
- To simplify and robustly handle the deletion of payment messages and their corresponding wallet history entries.
**Key Changes:**
- **HistoryModal Rendering:**
- Deleted transactions are now rendered with a consistent flat-design trash icon and the label "Deleted", with all details (amount, address, etc.) obfuscated or removed.
- Deleted transactions are visually faded and italicized for clarity.
- Clicking on deleted transactions is now disabled.
- **Delete Logic:**
- When a payment message is deleted, its corresponding transaction in `myData.wallet.history` is found by `txid` and all sensitive fields …
> Soft Delete for Payment Transactions in History Modal using message menu delete

- app.js
- Prevents users from launching invalid or unreachable URLs in the app, improving user experience and reducing errors.
- Added URL validation in the `LaunchModal`:
- When the user submits a URL, the app now attempts to fetch the URL using a `HEAD` request before sending it to the native app.
- The launch button is disabled and shows a loading state ("Checking URL...") during validation.
- If the URL is unreachable or times out, an error toast is shown and the user can try again.
- If the URL is valid, the original launch action proceeds as before.
- Button state is reset after the check, regardless of outcome.
- Error handling and user feedback are improved for a smoother experience.
> Validate URL Before Sending to RN in Launch Modal*

- app.js
- file name is no longer an underlined link
- the entire attachment-row div is now clickable to trigger download
- fix for https://github.com/Liberdus/web-client-v2/pull/588 moved hide toast to right after decrypt and download. In native app it was not getting triggered
> Make whole attachment div clickable for download

- app.js
- Refine reclaim toll error handling to avoid unnecessary error toasts when the toll pool is already empty.
- **Reclaim Toll Error Handling:**  
- Updated logic so that if a reclaim toll transaction fails with the reason `"user is trying to reclaim toll but the toll pool is empty"`, no error toast is shown. This prevents unnecessary alerts for a benign, expected condition.
---
- Reclaim toll transaction error handling in chat logic.
> Refine Reclaim Toll Error Handling to not show when toll pool is empty

- app.js
Problem: On mobile when downloading an attachment, a pop up blocked toast appears. It opens a dialog to either view or download, the popup blocked toast shows regardless of option picked.
Solution: Toast is removed and logging instead. Do not need to let user know opening in tab did not work.
> Update error handling for file download attempts by logging failed new tab openings instead of showing a toast notification.

- app.js
Introduce a flag to manage attachment download state, ensuring that multiple downloads do not occur simultaneously.
> Prevent concurrent downloads of attachments

- app.js
- Prevent users from adding attachments while a file is being encrypted and uploaded
- corrected `this.submitButton` in `worker.onerror` to `this.sendButton`
> Disable add attachment button during file encryption and upload

- styles.css
add word break to toast so that long unbroken file names wrap instead of overflowing off the screen
> Add word-break to toast so long file names wrap

- app.js
- Prevent users from sending duplicate invites to the same email or phone number within a session.
- Improve user experience by disabling the invite button during submission and providing clear feedback.
- Added a `Set` to the `InviteModal` class to track emails/phones already invited in the current session.
- Disabled the submit button immediately when the invite is submitted to prevent double submissions.
- On submission, checked if the email or phone has already been invited:
- If so, showed a toast message, cleared the input fields, and re-enabled the button for new input.
- After a successful invite, added the email/phone to the invited set to prevent future duplicates.
- Ensured the button state and input fields reset appropriately when the modal …
> Prevent Duplicate Invites and Improve Invite Modal UX

- app.js
- index.html
- styles.css
- To provide a clear way for users of the React Native app to check for updates by opening the appropriate app store page.
- To ensure the "Check for Updates" button is only shown to users running the app inside the React Native WebView, not to web browser users.
- **About Modal:**
- Added a "Check for Updates" button to the About modal's links section in `index.html`.
- The button is hidden by default via CSS and only shown if `window.ReactNativeWebView` is present (i.e., running inside the native app).
- When clicked, the button opens the correct store page (Google Play for Android, TestFlight for iOS) in a new tab, using the same `window.open(..., '_blank')` pattern as other external links in the app.
- **JavaScript:**
- Refactored the AboutModal …
> Add "Check for Updates" Button to About Modal for Native App Users

- lib.js
Remove the confirmation dialog in the linkifyUrls function to avoid triggering popup blockers.
> Prevent triggering popup blocker by removing link confirm dialog

- app.js
- Fix using function () { ... } with an arrow function () => {}
- added property for smoother scrolling experience on mobile
> Fix for messages not shifting up when the keyboard is opened

- app.js
- index.html
- network.js
- styles.css
If the user is not staked the stake info section will be hidden and instead a given a button that links to a (not yet implimented) validator info page
> Add stake info section and learn more button when not yet staked

- app.js
Enhance the user experience for multi-account users by prioritizing accounts that receive notifications, making it easier to switch to the relevant account when messages arrive.
• **Added notification handler** - Listens for `NOTIFICATION_TAPPED` events from React Native app
• **Implemented account prioritization** - When a notification is received for a different account, the user gets a choice to sign out immediately or stay signed in
• **Enhanced sign-in modal** - Accounts that received notifications appear first in the account selection list
• **Added automatic cleanup** - Notification priorities are cleared after any user signs in
• **Added helper methods** - `isCurrentAccount()`, `saveNotificationAddress()`, and `clearNotificationAddress()` for managing notification state
- …
> Handle notification click

- app.js
This improves user experience by visually distinguishing notified accounts in the dropdown list.
• **Visual Indicator** - Added bell emoji (🔔) next to account names that received notifications in the sign-in dropdown
1. **Notification received** → System checks if user is signed into the correct account
2. **Same account** → No action needed (ready for future chat modal integration)
3. **Different account** → User gets choice to switch immediately or stay signed in
4. **Next sign-in** → Notified account appears first in list with visual bell indicator
5. **After sign-in** → Notification priority is cleared for all accounts
The implementation provides a seamless way for multi-account users to quickly identify and switch to accounts that have received new messages, significantly improving …
> Enhance username selection in SignInModal by adding notification indicators for accounts associated with the notified address. 

- app.js
Refactor ReactNativeApp to store device and push tokens as class properties instead of global window variables. Update logic to handle native app subscription more effectively. This improves encapsulation and maintains state within the ReactNativeApp class.
> Subscribe right after receiving tokens from 'INITIAL_APP_PARAMS' message from RN

- app.js
- index.html
- styles.css
- **Stake Lock Validation**: Added client-side checks for unstake availability before transaction submission
- **UI Feedback**: Enhanced Validator modal with inline lock status messages and disabled button states
- **Performance**: Cached lock calculations to avoid redundant network calls
- **Lock Period Checks**: Validates three conditions before allowing unstake:
- Certificate expiration (`certExp > currentTime`)
- Validator active state (`rewardStartTime > 0 && rewardEndTime == 0`)
- Recent deactivation cooldown (`currentTime - rewardEndTime < stakeLockTime`)
- **User Experience**: Shows specific lock reasons and remaining time in tooltips and inline messages
- **Error Prevention**: Blocks unstake attempts with clear error messages instead of backend failures
- Added …
> Add client-side stake lock validation to Validator modal

- app.js
- index.html
- Prevents users from accidentally submitting the friend status form multiple times
- Improves user experience by providing visual feedback during form submission
- Fixes potential race conditions in friend status updates
- **Added submit button reference** - Store reference to submit button during modal load
- **Disable button on submit** - Disable submit button immediately when form submission starts
- **Re-enable button on modal open** - Ensure button is enabled when modal is opened
- **Re-enable button after completion** - Re-enable button after successful form submission and modal close
- **Prevent double submissions** - Button remains disabled during the entire submission process
The changes ensure that users cannot accidentally trigger multiple …
> Fix Friend Modal Submit Button State Management

- app.js
fixes an issue where notifications would not be check while app moved from background to foreground.
- sign out no longer removed the `visibilitychange` event listener
- moved add listener into DOMContentLoaded
> keep visibility event listener so notifications are checked on reopen

- app.js
- Implements proper rollback mechanism for failed friend status updates
- Removes redundant & unused `friend` field from transaction data
- Improves error handling and state consistency for contact status changes
- Ensures new contacts are properly initialized with rollback capability
- **Removed redundant transaction field** - Removed `friend: friend` from `update_toll_required` transaction to avoid data duplication
- **Added rollback state tracking** - Store `contact.friendOld` before updating friend status to enable rollback on failure
- **Simplified form validation** - Removed redundant null checks in `handleFriendSubmit` for cleaner code flow
- **Updated pending transaction data** - Changed `pendingTxData.friend` to `pendingTxData.to` for …
> Fix Friend Status Rollback and Transaction Cleanup

- app.js
- styles.css
Restyle video call messages to look like a button. The text is not longer a clickable link. 
Also adjusted the voice message button for sent messages to match so the button circle is visible.
> turn call link into a button

- app.js
- index.html
Adds a Share Invite Link button to the Invite Modal. It will try to invoke the device's native share sheet, if that is unavailable it will copy the invite to the clipboard.
Share message: "Message {username} on Liberdus! https://liberdus.com/download"
> Add share invite link functionality to Invite Modal

- app.js
Implement a 2-second cooldown on the Share button in InviteModal to prevent rapid submissions. 
Adjust error handling to rely on the cooldown for re-enabling the button, enhancing user experience during the invitation sharing process.
> Refactor: InviteModal handleSubmit disable `share invitation` button cooldown

- app.js
- index.html
- Introduced a reset button to clear the invite message input and restore the default text.
- Updated the open method to set the initial text based on saved message or default values.
- Enhanced user experience by allowing users to easily reset their invite message before sharing.
> Add reset and save message functionality to InviteModal for invite message input

- app.js
- index.html
Remove launch and update button functionality from `CreateAccountModal` in app.js and index.html. 
This change simplifies the modal by eliminating unused buttons and their associated event listeners. Now handled in the `WelcomeMenu`
> Remove `launch` and `update button` from `CreateAccountModal`

- app.js
Updated the message context menu positioning logic to prevent it from rendering off-screen when users tap message content near the bottom of the chat container, particularly addressing issues on older Android devices.
- **Modified `positionContextMenu()` function** in `app.js` to clamp menu positioning within `.messages-container` bounds
- **Replaced viewport-based positioning** with container-relative positioning using `getBoundingClientRect()`
- **Simplified overflow detection** using `Math.max/min` for cleaner boundary clamping
- **Added fallback positioning** to show menu above message when below placement would overflow
- Menu now respects chat container boundaries instead of just viewport edges
- Horizontal centering with left/right clamping within container
- Vertical positioning …
> Fix Message Context Menu Off-Screen Rendering on Android

- app.js
- Introduced properties to track keyboard visibility and initial viewport height.
- Implemented a resize event listener to detect keyboard state based on viewport height changes.
- Added a method to check if the keyboard is open, preventing context menu display when the keyboard is active.
> Add keyboard detection functionality in ChatModal to decide to render context-menu

- app.js
- index.html
- styles.css
- Added a new context menu option for editing and resending failed payment messages.
- Introduced methods to handle the deletion of failed payments and prefill the send form for resending.
- Updated context menu display logic to hide certain options for failed payments, enhancing user experience.
> Implement Edit & Resend functionality for failed payments in context menu of ChatModal

- app.js
Update balance check in WalletScreen to ensure proper handling of undefined values. This change enhances the reliability of balance updates by explicitly checking for undefined instead of relying on truthy evaluation.
> Fix false negative in updateWalletBalances due to truthy check

- app.js
Fix toll format mismatch that was causing "toll amount is incorrect" errors when sending chat messages after converting the toll system to USD-only input.
- After converting toll system to USD-only, chat message creation still expected tolls in LIB wei format
- `updateTollAmountUI` was setting `this.toll` to raw contact toll value (could be USD or LIB)
- `createChatMessage` expected `tollInLib` in LIB wei format
- This caused validation failures when contacts had USD-stored tolls
- Modified `updateTollAmountUI` to convert USD tolls to LIB wei before setting `this.toll`
- Ensures `this.toll` is always in LIB wei format for message creation
- Maintains USD display with LIB equivalent in UI
- Preserves backward compatibility for LIB-stored tolls
- Added conditional conversion: USD tolls → …
> Fix Chat Message Toll Validation Error

- app.js
Fixed orphaned account detection logic in `RemoveAccountsModal` to properly handle account keys with leading underscores (e.g., `_testl_627510f0cb0bf5e82b0cc8bace10a1a3649c74d9b733af9a32e26d495e5799fe`).
- **Updated parsing logic** in `RemoveAccountsModal.getAllAccountsData()` to handle keys with leading underscores
- **Improved username extraction** - now takes everything before the last underscore as username
- **Better netid validation** - uses last underscore-separated part as network ID
- **Added registration check** to ensure accounts aren't already registered before marking as orphaned
- **Simplified pattern matching** from rigid `username_netid` to flexible `*_address` format
- **Enhanced validation** for edge cases with multiple underscores
- **Maintained existing functionality** …
> Fix Orphaned Account Detection in RemoveAccountsModal

- app.js
User transaction type instead of memo to open staking modal from clicking stake/unstake txn in the history modal
> Use transaction type for clicking stake txn in history modal

- app.js
* Adjusted call time handling in CallInviteModal to reset the call time to 0 if it is within 5 minutes of the current timestamp, improving the logic for managing immediate call invitations.
* Enhanced the retrieval of call time from data attributes, ensuring it is consistently treated as a number for better type consistency.
> Update `CallInviteModal` to set `callTime` to 0 for calls about to happen within 5 of call time and after

- app.js
Retrieve public keys from the network if they are missing in the local contact data when initiating a call invite.
> Fetch missing public keys during call invite process

- app.js
- index.html
- styles.css
- **Replaced native datetime picker with custom date/time controls**
- Split UI into separate date input and time selectors (hour, minute, AM/PM)
- Date on its own line to prevent horizontal overflow in modal
- 12-hour format with AM/PM selection for better UX
- **Implemented 5-minute increment time selection**
- Rotating minute dropdown starting from default time
- Defaults to next 5-minute boundary (configurable via `DEFAULT_OFFSET_MINUTES`)
- Always resets to default time when modal opens
- **Fixed time display formatting**
- Rounds scheduled call times to nearest minute
- Removes seconds display to prevent artifacts like "5:34:99 PM"
- Uses locale-aware formatting for date/time display
- **Refactored modal class for maintainability**
- Added helper methods: `_pad2`, …
> Enhanced `callScheduleDateForm` with Custom Time Picker

- app.js
- index.html
- styles.css
**Purpose:** Add a dedicated Calls view accessible from Settings to display scheduled calls with join functionality.
- **Settings Integration:** Added "Calls" menu item at top of Settings modal with phone icon
- **New Calls Modal:** Created `CallsModal` class with list rendering similar to `HistoryModal`/`ChatsScreen`
- **Call Detection:** Scans all contacts' messages for `type: 'call'` with valid `callTime` within last 2 hours or future
- **Smart Filtering:** Only includes scheduled calls (excludes `callTime: 0` or missing values)
- **Interactive UI:** 
- Click username/time → opens chat with that contact
- Click phone button → joins call or shows "scheduled for..." toast for future calls
- **Modern Styling:** Vertically centered call buttons, clean list with …
> Add Calls Modal to Settings

- app.js
- Introduced `recordingStopTime` and `actualDuration` properties to track the end time and calculate the actual recording duration, excluding processing time.
- Updated `stopVoiceRecording` method to set `recordingStopTime` and compute `actualDuration` upon stopping the recording.
- Modified `getRecordingDuration` method to return the calculated `actualDuration` instead of the previous method of calculating duration based on the current time.
> Add recording duration calculation to VoiceRecordingModal

- app.js
- Failed video calls should not show a retry option in the context menu since video calls cannot be meaningfully retried like text messages
**Changes made:**
- Modified `FailedMessageMenu.open()` method to detect video call messages by checking for `.call-message` element
- Added conditional logic to hide retry option (`display: 'none'`) for video calls
- Ensured retry option remains visible (`display: 'flex'`) for regular text messages
- Failed video calls now only show "Delete for me" option in context menu
- Regular failed messages continue to show both "Retry" and "Delete for me" options
This change improves UX by removing the non-functional retry option for video calls while preserving retry functionality for text messages.
> Hide retry option for failed video calls in context menu

- app.js
Display a preview for deleted messages and ensure sent messages are prefixed with "You:" in the chat interface.
- Previously only payment and plain messages would show the deleted text when deleted. Now any message type ( call, vm, attachment, ect) will show the deleted text in the chat list preview.
- Previously only plain sent messages showed "You:" in front of the message in the chat list preview, now all message types sent by the user will be prefixed with "You:"
> Show deleted message and identify sent messages in chat screen preview

- app.js
- styles.css
Updates the styling in the call modal to highlight in progress calls.
- Call button on future calls in now grey
- Call button on in progress calls is now green
- Adds a 5 second interval to refresh and rerender the list and update button colors while the calls modal is active
> Highlight active scheduled calls in calls modal

- styles.css
- Added min-width: 0 to allow flex items to shrink below their content size.
- Set width: 100% for the mark class to ensure it takes the full width of its parent.
- Updated edit-field-input to also allow shrinking below content size.
> Enhance flexbox styles in styles.css in edit contact info for better responsiveness

- app.js
- index.html
> WalletScreen initial load to display -.-- instead of 0.00

- app.js
- A new debounced function was getting created on every input event which caused earlier timers from the first keystroke to not be cleared by later keystrokes. Added a memoized debounce function to fix this.
- fixed empty state not being shown when no messages matched the search
> Fix search message debounce

- app.js
For calls that are over 2 hours old, from the scheduled time or from send time for immediate calls.
- remove the call button and replace the text with "You called <username>"/"<username> called you"
- remove the Join and Invite options from the message context menu
> Remove call button from expired calls

- app.js
- styles.css
Adds an orange dot on the chat in the chats screen when the chat has a draft. Does not show the orange dot if there are unread messages.
> Add draft indicator to chat screen

- app.js
Disable long polling when the app is in the background while using the native app.
> Disable log polling in background for native app

- app.js
Fixed a bug with contact search input where searchText was out of scope and would always cause the delay to be 300ms, now it properly gets the text length from the event to determine length of the delay.
> Fix contact search debounce logic

- app.js
- default toll and min toll were still coming from the old network param values and have been switched to the new USDStr values in both new account creation and on the toll modal.
- Added error handling to minToll retrieval and calculation when opening the toll modal
> Update default and min toll to use the new USD String parameter values

- app.js
Moves validation check for new toll matching old toll into getWarningMessage and display the warning to the user to match the other validation errors. Previously the save button would be disabled without a warning message.
> Show warning message when toll is not changed

- styles.css
Remove the right border from amount fields to create a full border appearance. Affects the amount field in Toll, Send Asset, and Receive modal. Previously the currency button was connected to the field so the right border was removed. Now that the button is disconnected it should display a full border.
> Use full border on amount fields

- app.js
minor audit fixes
- Remove the unused event parameter from the backup account submission methods 
- in handleSubmitOne disable the submit button before anything else incase the saveState takes some time
- move url closer to where it is used
> Refactor backup account submission methods to remove unused event parameter

- app.js
This PR refactors the account removal modal to eliminate code duplication and provide better visibility into data loading errors.
**Key improvements:**
1. **DRY Principle**: Extracted `getContactsAndMessagesCount()` helper function that was duplicated between regular and orphaned account processing
2. **Better Error Detection**: Added explicit checks to distinguish between "no data exists" vs "decryption failed" scenarios
3. **User-Friendly Display**: Shows "unable to load data" instead of confusing "-1 contacts, -1 messages" or misleading "0 contacts, 0 messages" 
4. **Enhanced Logging**: Console warnings now specify whether decryption failed vs other errors
**Why this matters:**
Previously, when `decryptChacha()` returned `null` due to decryption failure, accounts appeared to have 0 …
> Refactor account removal modal: DRY up counting logic and surface decryption errors

- app.js
Update error handling in ChatModal to log warnings instead of showing toast notifications for offline toll processing
> Remove unnecessary toast for chatModal toll when closing modal

- app.js
Fix connectivity UI update logic in checkVersion function to ensure proper handling of network errors.
> Fix order of `markConnectivityDependentElements` and `updateUIForConnectivity`

- app.js
Remove inviteModal button selector from markConnectivityDependentElements function to allow function when app is offline.
> Remove inviteModal button selector from markConnectivityDependentElements

- app.js
Implement logic to disable the save button in TollModal when offline or if network ID mismatches, enhancing input validation handling.
> Keep offline TollModal  save button disabled when typing in input
